### ISSUE TITLE
Discussion before publishing

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/applet-window-title#1]

**Comment by psifidotos** [comment]
@kupiqu I found a little time to start this...

most of the features I had in my mind are already implemented but I need to clean it up a bit...
please check it out if you can

**Comment by kupiqu** [comment]
Great! First impressions look good.

Would you consider adding some functionality I have in my applet (some of them derived from AWC)?

- Title replacements
- Middle-click button
- Spacing between Icon and Title
- No window text and icon
- Tooltip

Also, it seems there is a vertical offset with respect to the global menu in my system (yours on the left, mine on the right):

![image](https://user-images.githubusercontent.com/3875196/48317637-eac51200-e5c2-11e8-9082-a90be7ce6d6e.png)

Btw, it seems your icons behave better than mine, I'll check your code to see if I can improve it in my code ;)

**Comment by psifidotos** [comment]
> Title replacements

I cant think why this is needed

> Middle-click button

for which action?

> Spacing between Icon and Title

isnt this the spacing?

> No window text and icon

the applet gets the text and the icon of the current activity.
So the user can set these accordingly and the applet will update the no window text and icon

> Tooltip

what info?

> Also, it seems there is a vertical offset with respect to the global menu in my system (yours on the left, mine on the right):

yes, and the question is whose fault is that missing 1px...
all other applets I am using in my system they have the same vertical alignment with my applet except the Global Menu

**Comment by psifidotos** [comment]
> LibreOffice Writer --> Writer

Sorry I dont fond the idea to change names from the official set application names

> Close

possible not... the actions that will be supported are going to be the same with the Latte Dock. I am not fond of the idea for the user to be able to close the current window by just middle clicking the entire panel so I will wait a few releases to take feedback from users

> I guess that's fine. I found cool the option to have a generic icon and the possibility to add extra text, e.g.:

I see... I dont really like this idea

> Having the whole window title in the tooltip may be useful when one has 2 or more instances of an application

hm, I will have to think this...

**Comment by kupiqu** [comment]
Ok, fair enough. I like all that functionality very much, and maybe other users do too, so I will keep using (and maintaining) my applet :)

**Comment by psifidotos** [comment]
> Ok, fair enough. I like all that functionality very much, and maybe other users do too, so I will keep using (and maintaining) my applet :)

yeah, no prob...

> Ok, fair enough. I like all that functionality very much, and maybe other users do too, so I will keep using (and maintaining) my applet :)

found it... I would had never thought it...

**QtControls.Label** and **PlasmaComponents.Label** do not return the same metrics... by using **PlasmaComponents.Label** instead fixes the alignment...
this is very important information and I think all plasma applet developers should know it....

**Comment by kupiqu** [comment]
>QtControls.Label and PlasmaComponents.Label do not return the same metrics... by using PlasmaComponents.Label instead fixes the alignment...
this is very important information and I think all plasma applet developers should know it....

I see, thanks for the note. My applet uses PlasmaComponents.Label, which I got from AWC

**Comment by kupiqu** [comment]
Mmm, I was thinking. I want the extra functionality that you are not that interested in, but I also want the nice infrastructure and latte compatibility that you have. So in principle I thought about two options, adding your infrastructure and compatibility to my applet, or adding the functionality I want on top of your code. This will be demanding and time consuming.

Then I got sort of a crazy idea... Do you think there could be a way to allow for plugins in applets? I guess it won't be easy at first (and perhaps it doesn't make much sense to you), but if possible I think it could be a nice easier way to create add-on functionality and a community which could more involved, both as devs and users of those extra features.

An example: in style you have application, title, etc. If your applet would manage plugins, perhaps a third source plugin could implement the replacements functionality, getting your style input and displaying the replacement (if it applies according to user's replacements) as the output. 

I guess this could somehow apply to other functionality as well... Anyways, a crazy idea :)

**Comment by psifidotos** [comment]
Sorry, I am not fond of plugins...

This applet is going to be the first of qml-only Latte capable applets that I have in my mind...

To support the specific Latte functionality you don't have to do something extreme, just disable your mouse area when your applet is in a Latte git version. You can watch in the code how this is identified.

**Comment by kupiqu** [comment]
It's getting better and better :)

**Comment by kupiqu** [comment]
I think it doesn't make sense to maintain publically 2+ applets for this. 

From the feature requests I mentioned above, the only one real important to me that is currently missing is the replacements. The activity name and its icon can be easily workarounded as you mentioned (by the way, it seems that the activity name is not properly displayed, it is capitalized by default, even if the actual name is not, is this intended?), the middle-click functionality is not that important in the end, and the tooltip that you may still be considering is a nice add but not fundamental.

I know that the replacement feature is not appealing to you, but could/would you please reconsider your decision? It's just a tiny piece of code that gives a lot of control to users (only if they want to) to fine-tune the display. I think users of my applet (including myself of course) very much like the feature.

**Comment by psifidotos** [comment]
> it is capitalized by default, even if the actual name is not, is this intended?

yes this is intended

> I know that the replacement feature is not appealing to you, but could/would you please reconsider your decision?

I could reconsider it when I get users feedback but only through editing applets properties in settings file, I dont like exposing it in the settings window

**Comment by kupiqu** [comment]
> > it is capitalized by default, even if the actual name is not, is this intended?

> yes this is intended

Any particular reason for that? Not strong feelings but I somehow prefer small case for activites, and same logic applies here, one can always capitalize the activity name in the activitiy settings if prefers that way.

> I could reconsider it when I get users feedback but only through editing applets properties in settings file, I dont like exposing it in the settings window

Sounds fair, thank you. And that option would be totally fine to me, and even easier to implement. All infrastructure for this is already in my applet. Well, the only thing that I'm not totally clear about is how to import the text replacements from the config file instead of from the settings window, but I guess it won't be too hard [ Perhaps you can orient me a bit on how to do this if eventually you decide not to implement this... ].

**Comment by kupiqu** [comment]
Now that the applet has been published, perhaps you prefer to close this issue and to have specific issues for remaining discussion (activity capitalization and replacements).

Please let me know if I should fill these issues...

**Comment by psifidotos** [comment]
Of course you can, it will be more constructive having different threads.
