### ISSUE TITLE
Request: Zero-width, when empty

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/applet-window-title#101]
I'm using this to show the current window's app icon, alongside your appmenu applet, at the expanding edge of a panel that's only as big as it needs to be.

When there is no active window (or desktop is active), this applet shows nothing, which is appropriate, but still takes up space.

![image](https://user-images.githubusercontent.com/1787385/84807053-a5559b80-afd4-11ea-96ba-cb1175da6a90.png)

![image](https://user-images.githubusercontent.com/1787385/84807042-a1c21480-afd4-11ea-8956-fc5e6ca1394c.png)

So my request is for the applet to not take up any space if it is not showing any content -- unless the dock or panel is in edit mode.

**Comment by psifidotos** [comment]
1. update to latest master
2. In Behavior page set the Placeholder text to be empty
