### ISSUE TITLE
Franz window title

### ISSUE THREAD

**Issue by Sadi58** [psifidotos/applet-window-title#102]
I use [Franz](https://meetfranz.com/) as a desktop client for WhatsApp, Telegram and Facebook Messenger.
As it doesn't have an option to start minimized or in the background, I use a startup script that launchs the app and then closes the window (wmctrl) keeping it running in the background.
At this stage, however, window title and menu remains until another window becomes active.
It might be caused by a bug in Franz (somehow its window appearing still active when closed but running in the background?), but I wonder if I can use a workaround for this.

**Comment by psifidotos** [comment]
what happens if you first minimize it and then let it run in the background?

**Comment by Sadi58** [comment]
> what happens if you first minimize it and then let it run in the background?
Window title disappears upon minimizing (xdotool) ), and reappears upon even closing (wmctrl) in that state!
Maybe I should try opening and closing a tiny app after Franz?

**Comment by Sadi58** [comment]
Sorry, sorry, this old man confused the Global Menu and Window Title widgets. :-(
