### ISSUE TITLE
The application title isn't at the centre of the panel

### ISSUE THREAD

**Issue by Jing-Linux** [psifidotos/applet-window-title#109]
Well, the left is this applet, next to it is the application name applet, then is the global menu.
![Screenshot_20210121_115654](https://user-images.githubusercontent.com/64244331/105278150-ddaeff00-5bdf-11eb-8aa0-bae708d92626.png)

**Comment by psifidotos** [comment]
did you try latest git master?

**Comment by Jing-Linux** [comment]
No... I install it through the kde add-ons installer.

**Comment by psifidotos** [comment]
I think this is already fixed, you can try master to check it out and report back.

**Comment by Jing-Linux** [comment]
Just tried.Nothing changed.

**Comment by psifidotos** [comment]
1. Are you using Plasma or Latte panel?
2. What is your plasma panel size if that is you are using?

**Comment by Jing-Linux** [comment]
Latte panel, 20 pixels.

**Comment by psifidotos** [comment]
increasing to 36px. does it help?

**Comment by psifidotos** [comment]
works just fine. In my system...

how did you install master verion?

[Application Title / GlobalMenu             -                     WindowAppMenu/Window Title]
![εικόνα](https://user-images.githubusercontent.com/2216474/105358890-6a1cea00-5bff-11eb-9d63-71c88603fb9c.png)

**Comment by psifidotos** [comment]
you probably didn't relogin after you installed master version

**Comment by Jing-Linux** [comment]
I did. I rebooted.

**Comment by Jing-Linux** [comment]
And sorry about the slow reply.
