### ISSUE TITLE
[bug] Title and application name isn't show, on a dual screen, when the window is on another screen

### ISSUE THREAD

**Issue by Zardoz89** [psifidotos/applet-window-title#11]
Firefox title and application name isn't show. I only get a "By default" ("Por omision", I have my local set to Spanish). I already try all Style options to change what text is show, and I keep getting the same text.

**Comment by kupiqu** [comment]
It seems weird. Firefox works just fine with my Catalan locale system.

**Comment by psifidotos** [comment]
I am still waiting the screenshot...

**Comment by Zardoz89** [comment]
I just discover that this issue only happens on multi monitor setups. If I move the firefox window to the main screen (where the applet-window-title container panel is), then is showed : 
![imagen](https://user-images.githubusercontent.com/888483/48616941-59281c80-e995-11e8-932d-856557109dad.png)

This happens with ANY application.

**Comment by psifidotos** [comment]
duplicate of #12
