### ISSUE TITLE
Window buttons don't load after updating to plasma 5.21

### ISSUE THREAD

**Issue by simifor** [psifidotos/applet-window-title#110]
It seems the applet is looking for libkdecorations2private.so.7, but since the plasma 5.21 update the version was bumped up to .8. As a workaround you can make a new link to the library and name it libkdecorations2private.so.7

**Comment by psifidotos** [comment]
Rebuild with latest master

**Comment by simifor** [comment]
> Rebuild with latest master

~~There are no build instructions in the readme and the aur package has the same issue (and doesn't actually seem to build anything, just move the files to the package)~~ I found that it was added to the repositories and the PKGBUILD of it actually compiles.
