### ISSUE TITLE
Microsoft Edge Title not being substituted 

### ISSUE THREAD

**Issue by TheBigWazz** [psifidotos/applet-window-title#111]
**Update:** Changing the app name to "Microsoft Edge" does activate the substitute, however the "(Dev)" appendix is being added after the substitution text. (See below) 

Is the appendix being added by Latte or by the Application? If latte recognizes "Microsoft Edge" as the app name, i'm not sure what is handling the appendix. 

Thanks for any help. 
![Edge_appendix](https://user-images.githubusercontent.com/80355486/110538289-bc936680-80d8-11eb-8f6d-9d1e59943eb1.png)

I've varified that "Microsoft Edge (dev)" is correct name for the application, however the Applet will not substitute it. Substitutions are working for other apps. Am I missing something?
![Edge_Name_Fail](https://user-images.githubusercontent.com/80355486/110522721-12aade80-80c6-11eb-88bd-723afbac3895.png)

**Comment by psifidotos** [comment]
show a screenshot of the Microsoft Edge window including also its titlebar

**Comment by psifidotos** [comment]
waiting for response.
