### ISSUE TITLE
Feature request: add fixed witdth option

### ISSUE THREAD

**Issue by adrianinsaval** [psifidotos/applet-window-title#112]
Hi! Could you include an option to have a fixed width so applets don't move around depending on active app? I guess you could say this is related to https://github.com/psifidotos/applet-window-buttons/issues/122 and https://github.com/psifidotos/applet-window-appmenu/issues/149
The general idea I believe is to have fixed width applets so nothing moves around when you change active app and you can more easily click the icons through muscle memory and not have to search around.

**Comment by maverick74** [comment]
Yeah!!! Revolution!!! Fixed Width!!! Fixed Width everywhere!!! Eh eh eh.

Now, seriously, I plus one this one as well :)

**Comment by trmdi** [comment]
This feature is available already.

**Comment by maverick74** [comment]
I'm sorry for my comment then. 
I did not checked it as I'm not using it, but thought that if I eventually do it would be useful for sure... That Was The reason of my comment. My apologies!

**Comment by adrianinsaval** [comment]
I see, sorry for the noise, the release version I installed doesn't have it
