### ISSUE TITLE
Set maximum size

### ISSUE THREAD

**Issue by Trollwut** [psifidotos/applet-window-title#113]
Would it be possible to at some kind of maximum size?

Two ideas I got in my mind:

1. Just limit to specific pixel width
2. give an option that if the selected text (title or app name) is longer than X chars, trim them down and add somethink like "..." at the end of it

**Comment by psifidotos** [comment]
1. is already provided in master version
2. I dont like it.

**Comment by Trollwut** [comment]
oh my god, I'm so blind... looked again and there it is. Sorry to interrupt!
