### ISSUE TITLE
Show some kind of menu indicator if menu is present when using "reveal appmenu on hover"

### ISSUE THREAD

**Issue by developer91234** [psifidotos/applet-window-title#115]
Some apps export menus, others don't. But when using the reveal on hover feature, you can't know whether a menubar is present or absent until you hover.

There should be some visual cue to tell the user that a menu bar is present, to save the user unnecessary mouse movements.
I'd suggest a menu icon be displayed when there's a menu.

This is just a common sense QOL improvement for the "reveal on hover" feature, which is really nice for small screens.

Thanks!

**Comment by Suor** [comment]
Sorry if that is a stupid question but how do you get "reveal appmenu on hover"?

**Comment by psifidotos** [comment]
> Sorry if that is a stupid question but how do you get "reveal appmenu on hover"?

It works only with Latte Dock. You need window title applet and window appmenu applet inside the same latte panel. Afterwards a setting is appearing in both of them to enable.

**Comment by Suor** [comment]
Tried with Latte Dock, no new settings in any of the widgets.

Using Manjaro, KDE 5.23.3. Installed `aur/latte-dock-git`, `aur/plasma5-applets-window-title`, `aur/plasma5-applets-window-appmenu` added both to a latte panel. Also tried `latte-dock` from non-aur repo.

![sublime-app-title-conf](https://user-images.githubusercontent.com/284103/145602581-a6b65ac5-de2e-463b-b3d6-3417bf85cdd0.png)
![sublime-appmenu-conf](https://user-images.githubusercontent.com/284103/145602588-7bf3d5db-15be-4707-95a0-a1f0542247bb.png)

**Comment by psifidotos** [comment]
The first applet is not the corrent one: this is the correct: https://store.kde.org/p/1274218/

on appmenu settings you can see the option but it is disabled until you install also Window Title.

**Comment by Suor** [comment]
Thanks, I figured it out. Menu does show on hover, but behavior is buggy:
- if activate with shortcut, i.e. `Alt-F` then can't close menu with `Esc` in some apps, e.g. Dolphin 
- if menu is visible via shortcut when switching to other app show menu of that app even though mouse is not over

**Comment by psifidotos** [comment]
Create new and separate bug reports and way to reproduce.

**Comment by developer91234** [comment]
@psifidotos why is this closed? @Suor 's questions have nothing to do with this feature request.
