### ISSUE TITLE
How can I substitute the "Default" activity name when I'm using another language?

### ISSUE THREAD

**Issue by dpkg-i-foo-deb** [psifidotos/applet-window-title#116]
So far this apples has given me a great experience as well as a different desktop look, but I have a little problem. 

I'm aware there is an option to add name substitutions in this plasmoid. However, I cannot add a substitution for the Default activity (My system language is set to Spanish.)

This is the activity name being shown when I'm in the desktop.

![Screenshot_20210627_213453](https://user-images.githubusercontent.com/80849765/123571331-9bda4400-d78f-11eb-8696-31aa5a0d5e0e.png)

And here are the substitutions I have set up in the settings.

![Screenshot_20210627_213710](https://user-images.githubusercontent.com/80849765/123571462-dd6aef00-d78f-11eb-838a-cba691ae1edc.png)

I have tried to replace "Por Omisión" with "Default" yet I cannot get it to work... Do I need to set up any special activity name? Thanks.

**Comment by dr460nf1r3** [comment]
![image](https://user-images.githubusercontent.com/12834713/123585105-22b01080-d7d2-11eb-82db-91c44fda273e.png)

**Comment by psifidotos** [comment]
1. Right click desktop
2. Show Activity Switcher
3. Click the Gear icon in your current Activity and set up whatever name you want

alternative way is to set up the placeholder text manually
