### ISSUE TITLE
[Question] How to retrieve active window title from command line

### ISSUE THREAD

**Issue by NICHOLAS85** [psifidotos/applet-window-title#119]
Hello! Sorry if this is the wrong place to ask but I'd love your help.

I'm currently using Wayland and due to how it's designed it has been very challenging to retrieve any window information through the means I'm most familiar with. Since this applet has the ability to display a window title depending on the active window I was curious if you knew of a simple script I could pass to `qdbus org.kde.plasmashell /PlasmaShell evaluateScript` which could print the title of the active window.

Again sorry if this is an inappropriate channel of contact and if it's not possible I appreciate your time!

**Comment by psifidotos** [comment]
I dont know any script way for this under wayland.

**Comment by NICHOLAS85** [comment]
Ah I found the documentation for Plasma Desktop Scripting and see it indeed does not expose that kind of information. I'll likely just fork applet-window-title and write the information I need to a file in `/run/` or similar for use with other programs. Thanks for your work on latte, applet-window-tile, and other projects!

**Comment by psifidotos** [comment]
Under wayland there is a chance that this would be considered a security bridge, these information are purposefully not exposed from desktop environments under wayland. It might be important that the user should be asked if it grants such exposer.

**Comment by NICHOLAS85** [comment]
I understand. For now, I've just added this functionality locally with a patch. We'll see where DEs/compositors go in terms of providing access to this information in the future. I believe GNOME has a solution just not KDE yet.
