### ISSUE TITLE
Window title displayed as "Default" when selecting a window from another monitor

### ISSUE THREAD

**Issue by dopauthor** [psifidotos/applet-window-title#12]
So appearently, when you have a multi-monitor setup (in my case 3 monitors) and have:

- 1 panel on 1 monitor
- 1 window on a different monitor selected

the window title just display "Default" instead of the actual window title.

--

Currently running latest KDE neon version.
uname-output:
Linux 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Plasmashell version: plasmashell 5.14.3

**Comment by psifidotos** [comment]
this is desired behavior... when there is no active window in the specific plasmoid screen then the current activity icon and name are displayed...

Change them according to your preference...

**Comment by dopauthor** [comment]
Is there a way to change it? There's no option in the Window Title configuration.

**Comment by psifidotos** [comment]
> I know how to rename an activity's name.

So why dont you nename it from "Default" to whatever suits you better?

**Comment by dopauthor** [comment]
That's not my problem. My problem is that even though a window on another monitor is focused, the applet just displays "Default". Why doesn't it display the title of the window I focused on an another monitor?

**Comment by psifidotos** [comment]
because it is in another monitor, that is a design decision and trend also for all active window applets

**Comment by dopauthor** [comment]
So that basically means that I'm not able to set an option to let the applet display the focused window titled independently from its monitor location?

**Comment by kupiqu** [comment]
Shouldn't this be coherent with taskbar's and, perhaps more importantly, the global menu behavior? Ideally the three should be coherent, at least if they are all in latte-dock panels. I guess this is not trivial to do though.

**Comment by psifidotos** [comment]
First the plasma global menu will decide what prefers and how...

Currently is considered a plasma menu limitation that will change in the future...

**Comment by kupiqu** [comment]
Sounds fair and good to me. Would you leave this issue open though as sort of a reminder...?

**Comment by psifidotos** [comment]
Yep... No prob...

**Comment by Zardoz89** [comment]
I would like to ask, what does OSX (as the reference of a popular desktop with a single menu with a polished and cohesive UX) when there is multiple screens. It show only a single global menu, or are duplicated on each screen, or each screen have his global menu that only shows the menu of the last focused window on these screen ?

**Comment by dopauthor** [comment]
> I would like to ask, what does OSX (as the reference of a popular desktop with a single menu with a polished and cohesive UX) when there is multiple screens. It show only a single global menu, or are duplicated on each screen, or each screen have his global menu that only shows the menu of the last focused window on these screen ?

From what I have found recently, OSX's global menu behaves like this Window Title Applet's original behaviour. So KDE's global menu is the actual 'design flaw' here in this case.

**Comment by psifidotos** [comment]
> From what I have found recently, OSX's global menu behaves like this Window Title Applet's original behaviour. So KDE's global menu is the actual 'design flaw' here in this case.

not for long... in 2-3 hours I will release the new Window AppMenu applet... that will provide a choice for the user: Filter By Screen... I have added to it all the goodness I am using in my system:

- minimize aware,
- multi-screen aware,
- same HIG settings windows with Window(s) suite applets
- ready for new Latte git painting...

**Comment by kupiqu** [comment]
> From what I have found recently, OSX's global menu behaves like this Window Title Applet's original behaviour. So KDE's global menu is the actual 'design flaw' here in this case.

I disagree, I don't see any design flaw anywhere, just different default behaviors. Said that, the best is having the option to choose as in the taskbar, and now, thanks to @psifidotos also in this applet and in the global menu.

**Comment by kupiqu** [comment]
> in 2-3 hours I will release the new Window AppMenu applet... that will provide a choice for the user: Filter By Screen... I have added to it all the goodness I am using in my system:
> 
> * minimize aware,
> * multi-screen aware,
> * same HIG settings windows with Window(s) suite applets
> * ready for new Latte git painting...

Awesome

**Comment by dopauthor** [comment]
> > From what I have found recently, OSX's global menu behaves like this Window Title Applet's original behaviour. So KDE's global menu is the actual 'design flaw' here in this case.
> 
> not for long... in 2-3 hours I will release the new Window AppMenu applet... that will provide a choice for the user: Filter By Screen... I have added to it all the goodness I am using in my system:
> 
> * minimize aware,
> * multi-screen aware,
> * same HIG settings windows with Window(s) suite applets
> * ready for new Latte git painting...

Wow, I'm already looking forward to trying it out.
Well, and sorry in advance if I'd been doing any trouble with creating this issue.

> > From what I have found recently, OSX's global menu behaves like this Window Title Applet's original behaviour. So KDE's global menu is the actual 'design flaw' here in this case.
> 
> I disagree, I don't see any design flaw anywhere, just different default behaviors. Said that, the best is having the option to choose as in the taskbar, and now, thanks to @psifidotos also in this applet and in the global menu.

That's why I put design flaw in quotation marks. :D

**Comment by psifidotos** [comment]
> Awesome

I am bored waiting plasma review process..
So I will provide now the experience and that will help users from older plasma versions such as plasma 5.12 and beyond to play with it...

I will wait for the community feedback in order how the three applets will provide the best experience to the user...

Now that I can play with all three applets codepage we can make them cooperate awesomely....

I mean when these three applets will be able to hide or not, and what information to show or not....

**Comment by kupiqu** [comment]
> I am bored waiting plasma review process..
> So I will provide now the experience and that will help users from older plasma versions such as plasma 5.12 and beyond to play with it...
> 
> I will wait for the community feedback in order how the three applets will provide the best experience to the user...
> 
> Now that I can play with all three applets codepage we can make them cooperate awesomely....
> 
> I mean when these three applets will be able to hide or not, and what information to show or not....

Sounds great! 

And this will probably fix #15 for @Chromace as well.

**Comment by kupiqu** [comment]
I wonder, can you have more than one active window if they are in different screens? Otherwise, it's a bit tricky, isn't it? I mean, there will be title, menu and buttons for a window that is no further active as the active one is in a different screen :/

**Comment by kupiqu** [comment]
> > I mean, there will be title, menu and buttons for a window that is no further active as the active one is in a different screen
> 
> this is not what will happen at all cases... both three applets are screen aware capable... so when the active window is in different screen:
> 
> 1. Window Title can show the current activity and icon instead
> 2. Window Buttons are capable to not be shown at all
> 3. the app menu will not be shown at all

Yes, that's right and makes total sense. Just thought that in that case it would 'feel' right to have an active window per screen, and got a bit confused.

**Comment by kupiqu** [comment]
In other words, the applets could be screen specific but the tracking of current active window is either way global (i.e., never screen specific).

**Comment by psifidotos** [comment]
https://github.com/psifidotos/applet-window-appmenu
