### ISSUE TITLE
Problem with long titles and appmenu applet

### ISSUE THREAD

**Issue by prkteja** [psifidotos/applet-window-title#123]
I have a fairly common setup with the Window title applet and Appmenu applet next to each other

Currently, if the length in Title applet is set to '_Based on Contents_', the appmenu overflows onto the right aligned widgets when the title is too large
![Screenshot_20211210_213318](https://user-images.githubusercontent.com/48997655/145606433-9a730854-dd02-44a1-a80e-9cefbd34f078.png)

This can be fixed by setting the length to '_Fill available space_'. But now, the appmenu is always aligned to the right
![Screenshot_20211210_213119](https://user-images.githubusercontent.com/48997655/145607448-8421f80e-fa03-4154-afda-6898b079805a.png)

My current workaround is to set the Title length to '_Maximum_' and leave enough space for appmenu. But when there is no menu, the title will truncate and show '...' even when there is lot of space next to it, making it look weird.
![Screenshot_20211210_213405](https://user-images.githubusercontent.com/48997655/145608087-29d101ad-d346-4223-9237-7a23a06f44d6.png)

Ideally, I want both the applets to always remain next to each other, not overlap with anything else, and the title to truncate only when there is no empty space left on the panel.

I'm using latte dock v0.10.4 and latest applets.

**Comment by psifidotos** [comment]
what you are asking in not possible with QML Layout infrastructure it breaks also for plasma panels... you need to find an alternative to handle this.

**Comment by psifidotos** [comment]
then only workable alternative is:
 1. Window Title: set Maximum
 2. Window App Menu: "Always use maximum available width"

In Latte when appmenu contents overflow it will give you an option to scroll between them...

**Comment by prkteja** [comment]
Thanks for the alternative workaround, it is pretty close to what I want :)

I have one more suggestion, if possible -
If the appmenu is scrolling and if there is title applet next to it, enable the hover effect on title and remove the menu.
We already have a toggle to do this manually. If we can also have a toggle to enable this dynamic behavior, it would be a nice feature.
