### ISSUE TITLE
A dash should be used instead of a hyphen

### ISSUE THREAD

**Issue by felagund** [psifidotos/applet-window-title#124]
Typographically, hyphen ("-") is used for connecting words together. To separate words, dashes are used, mostly m-dashes "—". That is also what KWin is using:
![Screenshot_20211228_195039](https://user-images.githubusercontent.com/1218098/147597654-56226a42-f894-49fb-9c86-6dc1686156ac.png)
:

**Comment by psifidotos** [comment]
Kwin is not consistent in that regard and there are plenty of cases that uses one or another.

Sorry I don't consider this a bug. I totally prefer small dashes that have a much lighter visual footprint.

**Comment by felagund** [comment]
There are (at least) three things:
Hyphen: -
n-dash: –
m-dash: —

Right now what is there is a hyphen and that is definitely wrong. I myself do not make much difference between m- and n-dashes but hyphens should not bave blanks around them. (the pandemic of hyphens as opposed to dashes is fully a function of hyphens being on keyboards). I cannot comment about Kwin, I just looked at what was used on my install, not sure where else they use something else. It just looks rather inconsistent like this.

By the way, I just noticed anoher issue - obviously I have opened a file called "bread" - yet it is capitalized in the applet ("Bread"). That can be an issue in a case-sensitive filesystem. Not sure if it is the applet's doing though.

**Comment by psifidotos** [comment]
You can disable first letters capital option.

**Comment by felagund** [comment]
Ok, I disabled it. I guess it would be a better default to have it disabled. Regarding the dash/hyphen thing - I will just put this link here: https://practicaltypography.com/hyphens-and-dashes.html so that it does not look like it I am making it up:-).

**Comment by psifidotos** [comment]
I will try them and check results...

**Comment by felagund** [comment]
By the wayit is Qt5 doing this: https://code.woboq.org/qt5/qtbase/src/plugins/platforms/xcb/qxcbwindow.cpp.html#2586
but I think it is a sensible behaviour.

**Comment by felagund** [comment]
Is it possible the applet is changing the window title in some way? It displays Firefox with a hyphen even though Firefox specifically sets a dash, as can be seen in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1751584
