### ISSUE TITLE
Truncate long titles in the middle

### ISSUE THREAD

**Issue by felagund** [psifidotos/applet-window-title#125]
The LIM implementation already does it like that and I think for a reason - important information tends to be at the end of filename - namely extension and sometimes version (if people work by exchanging files, they will often add something like "_ver5" at the end. See what I mean here:
![Screenshot_20211230_235547](https://user-images.githubusercontent.com/1218098/147793932-6a5e2bd8-0820-4e78-b9c8-9765ec86e3ca.png)

If it could be changed like that, that would be great!

**Comment by felagund** [comment]
This has been fixed here, no? https://github.com/psifidotos/applet-window-title/commit/093516cd226ac26e3ce8e40c704459de69257e19

**Comment by psifidotos** [comment]
yep, fixed
