### ISSUE TITLE
Some apps use symbolic icons

### ISSUE THREAD

**Issue by alschaapman** [psifidotos/applet-window-title#127]
When configured to display an icon, applet-window-title displays a symbolic (low-detail, monochrome) icon for some applications, but not others. I have observed this with VLC and Konversation so far.

**Comment by psifidotos** [comment]
not this applet responsibility

**Comment by alschaapman** [comment]
Thanks for the speedy response. Could you give me any information on where the applet receives the icon information from, so I could consider troubleshooting it in some other context?

**Comment by psifidotos** [comment]
that one https://github.com/KDE/plasma-framework/blob/master/src/declarativeimports/core/iconitem.h
but is probably your icon theme problem and not the iconitem one.
