### ISSUE TITLE
Text color (enhancement)

### ISSUE THREAD

**Issue by ilkerhk** [psifidotos/applet-window-title#132]
Hi,
It would be great if you add an option to change the text color. 
This would be helpful when it is used with the global-menu widget because the user can visually distinguish their border. 

(I use it with Title is shown and it is long therefore it is sometimes not clear where the title ends and the global menu starts. )

thanks for the nice work.

**Comment by psifidotos** [comment]
sorry not interested

**Comment by ilkerhk** [comment]
No problem,
Here is a simple workaround if anyone is interested in (see attached screenshot). 

#  Make the text color of global-menu yellowish 
sudo sed -i 's/color: background.state == MenuDelegate.State.Rest ? palette.windowText :/color: background.state == MenuDelegate.State.Rest ? "#FFE0A0" :/g' /usr/share/plasma/plasmoids/org.kde.plasma.appmenu/contents/ui/MenuDelegate.qml   



![Screenshot_20220604_180358](https://user-images.githubusercontent.com/13827163/172010367-1dcb8fee-9907-4c82-acce-b42bafc5bb56.png)
