### ISSUE TITLE
[feature request] Hide on mouse hover

### ISSUE THREAD

**Issue by impresionista** [psifidotos/applet-window-title#133]
It would be nice to hide the the applet on mouse hover, maybe with a slide-out animation. The idea is that if you have an focused window, the applet shows application/title but if you hover it it disappears and lets the space to be replaced whit another applet. Matching this behavior with an option to show on hover in [Global Menu applet](https://github.com/KDE/plasma-workspace/tree/master/applets/appmenu) could help to save space showing only one of them at a time (this is similar to Ubuntu Unity behavior).

**Comment by psifidotos** [comment]
You need: Latte Panel + Window Title applet + Window AppMenu applet.. Afterwards the two mentioned applets provide you an option for this... With Plasma panels and current applets implementation this is not possible.

**Comment by impresionista** [comment]
Ok! Thanks for the repply! I wasn't using AppMenu so I've never noticed that interaction.
