### ISSUE TITLE
Feature Request: Change/Hide "Default" Text

### ISSUE THREAD

**Issue by scorpius2k1** [psifidotos/applet-window-title#134]
**Apologies if I am missing a detail if the feature is already there.**

Currently, if I do not have any windows visible, there is a default test "Default" that always shows (Ex. https://i.imgur.com/O94PjoO.png). Is there any way to hide/change the text that is displayed as a placeholder? Another feature that would be useful is a "Default" icon that could be set in addition to this.

Appreciate the great work, thank you for creating these useful features for KDE!

**Comment by darkoverlordofdata** [comment]
This works on one of my computers, but not they other :) I notice the one that works is  v1.1. I installed it via  "Add Widgets -> Get New Widgets". After installing Ubuntu on a 2nd computer, that option fails, so I installed it via github. I got version 0.7.0. I don't see a release here for 1.1. This seems confusing.

**Comment by scorpius2k1** [comment]
Thanks for your reply @darkoverlordofdata 

I've forked this project and made a few fixes including hiding the "Default" text, and showing titles properly for non-native apps such as Wine, Java, etc which normally are just blank when using the "Application" Text Style.

If you want to use my feature patch, just clone this repo:
[https://github.com/scorpius2k1/applet-window-title](url)

Then, in the root folder (where README.md exists), just run the command and re-login to KDE:
plasmapkg2 -u .

Hopefully if others find this useful, @psifidotos will have a look and possibly merge into an update.

**Comment by kellerman** [comment]
> Thanks for your reply @darkoverlordofdata
> 
> I've forked this project and made a few fixes including hiding the "Default" text, and showing titles properly for non-native apps such as Wine, Java, etc which normally are just blank when using the "Application" Text Style.
> 
> If you want to use my feature patch, just clone this repo: https://github.com/scorpius2k1/applet-window-title
> 
> Then, in the root folder (where README.md exists), just run the command and re-login to KDE: plasmapkg2 -u .
> 
> Hopefully if others find this useful, @psifidotos will have a look and possibly merge into an update.

Thanks for your fixes. Although wine apps now show properly, the desktop view still shows the Default text and no icon for me on latest stable KDE Plasma on Arch linux.

**Comment by scorpius2k1** [comment]
> > Thanks for your reply @darkoverlordofdata
> > I've forked this project and made a few fixes including hiding the "Default" text, and showing titles properly for non-native apps such as Wine, Java, etc which normally are just blank when using the "Application" Text Style.
> > If you want to use my feature patch, just clone this repo: https://github.com/scorpius2k1/applet-window-title
> > Then, in the root folder (where README.md exists), just run the command and re-login to KDE: plasmapkg2 -u .
> > Hopefully if others find this useful, @psifidotos will have a look and possibly merge into an update.
> 
> Thanks for your fixes. Although wine apps now show properly, the desktop view still shows the Default text and no icon for me on latest stable KDE Plasma on Arch linux.

Glad to help! That's very odd you are having that issue because I too am using KDE Plasma on Arch Linux (fully updated) and I do not see that happening on my end.  It works fine with any "Text Style" set in the config menu - I have mine set to "Application", but tested on all and working as intended (no icon or text). Not sure what it could be, apologies. Maybe try completely removing and re-installing the applet?

**Fwiw, my sys/versioning info from "KDE About This System":**
Operating System: Arch Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.4-zen1-1-zen (64-bit)

**Comment by kellerman** [comment]
If I uncheck "Show activity information", then I can enter custom text, which will be shown instead of "Default", which is of course better, but there is the icon missing.

**Comment by scorpius2k1** [comment]
> If I uncheck "Show activity information", then I can enter custom text, which will be shown instead of "Default", which is of course better, but there is the icon missing.

Glad you figured out a solution for the text. IIRC, I don't believe an icon was ever visible for the Default/Desktop level, even with @psifidotos original code. Without digging into the project, I assume the applet simply goes off of what the system provides as the app icon, if there isn't one, then nothing shows. It would have to be added as an option (ie, choose default/custom icon for windows with no icon). This is a bit out of my scope with what I what I intended to accomplish with my fork of this project. I would recommend to open a pull request here to possibly add in future releases.

**Comment by scorpius2k1** [comment]
After looking further into this, unchecking "Show activity information" and leaving the field blank will hide the "Default" text altogether. The only issue is leaving it completely blank, you will not be able to access the options unless opening a window with a title. An alternative workaround is to place a single empty space into the placeholder field. Maybe an option/checkbox could still be added to automatically "Use Whitespace" as a placeholder.
