### ISSUE TITLE
left vs. right margins look asymmetrical (window title + global menu layout)

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-title#14]
I guess most users (but probably not all) set the window title applet on the left and the global menu on the right.

In this configuration, I "see" an asymmetric margin between left and right. The margins set by the window title applet are in fact symmetrical but given that the global menu is implemented as buttons, which have internal margins, the apparent margin on the right (which is what I guess most users care about) is visually larger than the margin on the left.

Do you think the applet could compensate for that as an option?  In any case this should be default behavior as not all users shall display "window titlle + global menu"

[ Side note: This was one of the reasons why I gave three instead of two spacing options in my applet (left, right and in between). This is probably not needed if given the option to substract the (inside) button margin from the window title right margin, so that the total left and right margins look completely symmetrical in the panel view. ]

**Comment by psifidotos** [comment]
The margins do not have to be symmetrical just unlock the locker

**Comment by kupiqu** [comment]
Oh, I see. That's great. I totally missed it!
