### ISSUE TITLE
Misaligned vertical positioning of title

### ISSUE THREAD

**Issue by Chromace** [psifidotos/applet-window-title#15]
As shown in the below screenshot, the applet's title is not properly vertically centred in comparison to, say, the global menu applet next to it. The expected result would be to have it properly in the centre.

![image](https://user-images.githubusercontent.com/16624211/48551862-d5d1e100-e92a-11e8-8313-67e5d4a6079b.png)

**Comment by psifidotos** [comment]
Did you try master version?

**Comment by Chromace** [comment]
Yes. I directly cloned the GitHub repo and installed the applet from there.

**Comment by psifidotos** [comment]
Problem is that it isn't title's fault... Probably the next days I will fork plasma app menu, it will be one of the things to fix in app menu

**Comment by Chromace** [comment]
A comparison might be more apt.

![image](https://user-images.githubusercontent.com/16624211/48599648-bdaaa200-e9bc-11e8-9e51-4bfac88b3fe5.png)

The left applet is from https://github.com/kupiqu/plasma-active-application
The right one is the master version of this current application. Perhaps there's something in the former that's missing from this one?

**Comment by psifidotos** [comment]
Show me your Window Title settings please

**Comment by psifidotos** [comment]
@kupiqu are we OK with this? Has this been fixed for you by the master version?

**Comment by Chromace** [comment]
![image](https://user-images.githubusercontent.com/16624211/48612176-4b49ba00-e9dc-11e8-95cb-94a825b32059.png)
Here are the settings. Hopefully there's nothing abnormal about them?

**Comment by kupiqu** [comment]
It works fine in my system

**Comment by Chromace** [comment]
Smaller panel sizes make for a much clearer misalignment.
![image](https://user-images.githubusercontent.com/16624211/48649719-a4026c80-ea47-11e8-8cb3-1f38526e3929.png)
This is Latte dock at 16px - the title of the applet is not centred compared to other components.

**Comment by kupiqu** [comment]
did you try with all the new https://github.com/psifidotos/applet-window-appmenu ?

**Comment by Chromace** [comment]
Might have found a relevant commit in Active Window Control that's causing this problem.
https://phabricator.kde.org/R884:1119c47f1756be9d302327f51c31f25e0f4d4e56
