### ISSUE TITLE
Option to hide title on desktop when no app is in foreground

### ISSUE THREAD

**Issue by himsin** [psifidotos/applet-window-title#17]

**Comment by psifidotos** [comment]
can you explain me ?

**Comment by himsin** [comment]
Here --> https://imgur.com/a/gTScCAW

I want to hide "Default" title on top panel or atleast that blank space for icon should not be there.

This also shows up if I have an app open (dolphin in this case) and I click on desktop (dolphin is no longer active window). see 2nd screenshot

2nd screenshot is also showing an issue of appmenu. Dolphin is no longer active, as I have clicked on desktop and yet app menu is visible.

**Comment by psifidotos** [comment]
> This also shows up if I have an app open (dolphin in this case) and I click on desktop (dolphin is no longer active window). see 2nd screenshot

what you see is the current Activitiy name and Icon


> 2nd screenshot is also showing an issue of appmenu. Dolphin is no longer active, as I have clicked on desktop and yet app menu is visible.

has been fixed in master by giving you a choice from settings window

**Comment by psifidotos** [comment]
you can change the Activity name from Default to whatever you want even empty string...

**Comment by himsin** [comment]
I also tried substitution but it's not working. Not sure if I'm using it correctly. Do we need to use commas or any other delimeter?
Here--> https://imgur.com/a/qrqipVn

**Comment by psifidotos** [comment]
substitutions dont apply at activity information... I added a filter for this as settings window

**Comment by trmdi** [comment]
@psifidotos 

Btw, I think you should give 2 default substitution entries to teach users how to use that feature a bit more detail.
The 2nd entry could be "Gimp.*" -> "Gimp" (to show that they can use a RegExp)

**Comment by himsin** [comment]
Thanks, it's working fine now
