### ISSUE TITLE
Unified scroll behavior in manage substitutions

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-title#22]
If  there are > 5-6 substitutions, correspondence between `matching` and `replace with` is easily lost.

![image](https://user-images.githubusercontent.com/3875196/48957656-f6e89200-ef27-11e8-8454-6e77913bab31.png)

One solution for this wculd be a table but it's fine you find them ugly, and I agree that, other than because of this, current solution is quite good too... 

So I would suggest that the scroll bar of match and replace with would be linked, so moving one would move the two fields so correspondence is always paired.

An alternative to this, although less good would be allowing resizing of the pop-up, and somehow keeping the size for next calls.

**Comment by kupiqu** [comment]
Forgot to say that I came to this because at some point I opened qGit and saw Libreoffice title, the result of improper pariring after editing the lists... :)

**Comment by psifidotos** [comment]
> So I would suggest that the scroll bar of match and replace with would be linked, so moving one would move the two fields so correspondence is always paired.

yep, that sounds good. Can you provide a pull request for review?

**Comment by kupiqu** [comment]
> yep, that sounds good. Can you provide a pull request for review?

Unfortunately I have no idea how to do it :(

**Comment by psifidotos** [comment]
Living this open until someone that can implement the smart scrollbar is also a solution and I prefer it

**Comment by kupiqu** [comment]
Found this that may be particularly relevant:

https://stackoverflow.com/questions/45941179/scroll-two-or-more-list-views-in-qml

**Comment by kupiqu** [comment]
> Found this that may be particularly relevant:
> 
> https://stackoverflow.com/questions/45941179/scroll-two-or-more-list-views-in-qml

@psifidotos Could you please take a look and see whether this could be an option for window-title and, if so, foresee how easy/difficult it would be to implement?

**Comment by kupiqu** [comment]
> @psifidotos Could you please take a look and see whether this could be an option for window-title and, if so, foresee how easy/difficult it would be to implement?

If you think it's feasible and relatively easy thing to add, I could try to implement it and, if I succeed, send a pull request

**Comment by kupiqu** [comment]
More particularly, would be having only one scroll bar be good, or you definitely want to keep having two?

**Comment by kupiqu** [comment]
done

**Comment by psifidotos** [comment]
very nice !!!

fixed with: https://github.com/psifidotos/applet-window-title/commit/58c4fc9f77fa41482911506e73e1770ae51cda4b
