### ISSUE TITLE
No changes in 0.2-1or git version visible

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/applet-window-title#23]
I was eager to get 0.2-1 features so I installed previously git version. I didn't see any improvements, all was exactly as on 0.1. I assumed, something may be wrong with my install.

Today a new version showed up officially. I installed it and... I see the same problem. No changes. It still looks like v0.1. The same options, the same bugs. Nothing new and nothing like on the screen you posted.

Can someone else confirm that or is it just me?

I specially uninstalled the applet with its config using:

`sudo pacman -Rn plasma5-applets-window-title`

Then installed it via AUR again, rebooted latte. PKGBUILD points to the release version so all seems to look good and yet no new features are to be seen.

**Comment by psifidotos** [comment]
The window title applet is plain qml. It can be installed and updated through Widgets Explorer.

You have installed both from Widgets Explorer and AUR decide what you prefer...

**Comment by michaldybczak** [comment]
Ah, that was the problem all along! Then the plasma applet panel is broken. I did removed it and it showed as removed and yet I had applet files in my user directory. After I deleted it, I see finally new features and bigs are gone. Great!
