### ISSUE TITLE
New option - custom icon on desktop view

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/applet-window-title#25]
We are missing the option to add a chosen icon for the desktop view like it was possible in AWC.

Currently, the look is screaming: aren't we missing something ;)?

![screenshot-2018-11-24-21-50-57](https://user-images.githubusercontent.com/10132958/48972828-11f3f880-f033-11e8-8ffd-b328ec9d91f3.png)

The applet is reserving space for the icon but of course, none is shown because we can't specify any.

I would like to add Manjaro icon there, some will add tux icon or... mac icon ;p. Whatever, this is fun and looks cool.

**Comment by psifidotos** [comment]
Change your Activity icon and name accordingly

**Comment by michaldybczak** [comment]
There is a way to add an icon to activity??? Uh... Will look.

**Comment by michaldybczak** [comment]
Aaa, works! Thanks, didn't know this option ;P

**Comment by psifidotos** [comment]
such an option is also a good way for users to learn some more default plasma customizations.... ;)

**Comment by psifidotos** [comment]
my activities...

![default](https://user-images.githubusercontent.com/2216474/48972906-d4946880-f03c-11e8-8d93-90f573190b8f.png)

**Comment by michaldybczak** [comment]
Looks awesome!

There were talks about getting rid of activities but I and some others added our reasons why this should stay and why we love it. Now it got quiet so let's hope they just decided they have bigger issues to solve.
