### ISSUE TITLE
Feature Request: Elide only title like in titlebar

### ISSUE THREAD

**Issue by moffis** [psifidotos/applet-window-title#27]
When a window's titlebar becomes too small to render the full title and application name at least the application name is still being rendered and only the title is elided.
Can we have this, too?

![title1](https://user-images.githubusercontent.com/45194295/49242191-72f04780-f40a-11e8-9fc3-1022bd73c808.png)
![titl2](https://user-images.githubusercontent.com/45194295/49242190-72f04780-f40a-11e8-9ce0-52b6c60ce5fb.png)
![title3](https://user-images.githubusercontent.com/45194295/49242192-72f04780-f40a-11e8-8ef3-be0ab320f20b.png)

**Comment by psifidotos** [comment]
yep, that makes sense...
