### ISSUE TITLE
[Feature request] Add an option to customize the "Plasma" title 

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-title#3]
Some users prefer to display some other interesting title to the default "Plasma".
E.g: I'd like to be able to display "Plasma desktop <3", it shows my happiness when I'm sitting in front of awesome KDE stuff like Latte, applet-wnidow-buttons, applet-window-title ....

**Comment by rokups** [comment]
Looks like it displays name of current activity. At least in my case it does and text was `Default`. You can try changing name of current activity for that end as a workaround.

**Comment by trmdi** [comment]
@rokups 
Oh, I didn't thought about this. It works. Thank you.

@psifidotos You can close this if you want.
