### ISSUE TITLE
Window title is not elided when digital clock plasmoid is placed in the middle

### ISSUE THREAD

**Issue by fezu54** [psifidotos/applet-window-title#32]
I've placed the "Digital Clock" and the "Appliation Launcher" widget in the middle of my top latte bar:

![screenshot_20190102_125517](https://user-images.githubusercontent.com/4998526/50591026-bf0d2c80-0e8d-11e9-9406-d8d14c587b15.png)

In case of the window title is longer than actual space is left, the title is not elided. Instead of it is expanded underneath the two plasmoids:
![image](https://user-images.githubusercontent.com/4998526/50591088-0bf10300-0e8e-11e9-8fe0-8183d7b084a7.png)

Expected behavior:
* Elide the string when space is gone

Awesome behavior:
* Elide the string starting with the clock and resume it after the application launcher.

Additional information:
To ensure that the clock and the application launcher is always in the middle,   I put the two justify splitter around them:
![image](https://user-images.githubusercontent.com/4998526/50591254-ea444b80-0e8e-11e9-92dd-624576042292.png)

**Comment by psifidotos** [comment]
> Elide the string starting with the clock and resume it after the application launcher.

not possible... extreme complexity with no real benefit...

> Elide the string when space is gone

makes sense but it is much harder to implement than it sounds

**Comment by psifidotos** [comment]
>  There, it was able to elide the title string correctly.

feel free to report back your findings

**Comment by fezu54** [comment]
Why did I know that you would say something like this? :yum:  :smile:  I will have a look into the code of it, even though my QML skills are very modest.

**Comment by psifidotos** [comment]
testing with latest master, this could be worked around a bit if the user sets a specific length from settings menu

**Comment by fezu54** [comment]
I've looked into the code of the Active Window Control plasmoid and found the following snippet:
```
PlasmaComponents.Label {
                id: windowTitleText

                property double iconMargin: (plasmoid.configuration.showWindowIcon ? iconItem.width : 0)
                property double properWidth: parent.width - iconMargin - iconAndTextSpacing
                property double properHeight: parent.height
                property bool noElide: fitText === 2 || (fitText === 1 && mouseHover)
                property int allowFontSizeChange: 3
                property int minimumPixelSize: 8
                property double iconMarginForAnchor: noWindowActive && plasmoid.configuration.noWindowIcon === '' ? 0 : iconMargin
                property bool limitTextWidth: plasmoid.configuration.limitTextWidth
                property int textWidthLimit: plasmoid.configuration.textWidthLimit
                property double computedWidth: (limitTextWidth ? (implicitWidth > textWidthLimit ? textWidthLimit : implicitWidth) : properWidth) - activeWindowListView.buttonsBetweenAddition

                anchors.left: parent.left
                anchors.leftMargin: windowIconOnTheRight ? 0 : iconMarginForAnchor + iconAndTextSpacing + activeWindowListView.buttonsBetweenAddition
                anchors.top: parent.top
                anchors.bottom: parent.bottom
                verticalAlignment: Text.AlignVCenter
                text: plasmoid.configuration.noWindowText
                wrapMode: Text.Wrap
                width: computedWidth
                elide: noElide ? Text.ElideNone : Text.ElideRight
                visible: plasmoid.configuration.showWindowTitle
                font.pixelSize: fontPixelSize
                font.pointSize: -1
                font.weight: fontBold || (appmenuBoldTitleWhenMenuDisplayed && appmenu.visible) ? Font.Bold : theme.defaultFont.weight
                font.family: fontFamily || theme.defaultFont.family
```

For me, it looks like it is calculating the needed width in some way. I played around a bit with your code but wasn't really successful. 
Do you have any advice how to debug the qml code? 
I know how to program, but unfortunately I am a Java guy. So I would need some little help with setting up a development environment to really investigate this issue.

**Comment by psifidotos** [comment]
@fezu54 I found a a way yesterday but first I want to make sure that Latte behaves properly with applets that fill the remaining space in a panel

**Comment by kupiqu** [comment]
This commit broke behavior in my system (in Latte 0.8.4). Before this commit I set in settings `length` to none (maximize), and appmenu applet appeared right after the title applet with proper separation. After the commit, there is a long gap in between, so there is no way to achieve same behavior as before, as all I can do is setting a static separation, which doesn't work given the variable length of application names and window titles.

**Comment by kupiqu** [comment]
> Maximum means use all free space from panel, setting a length of 255px means that the maximum length would be 255px. titles that are below 255px. should not leave a gap.

Sounds good in terms of Maximum (I was surprised myself about previous behavior to this regard), but then we need a Minimum setting (that accounts for the full length of the applet). Following your example, I don't want to elide the application name if it is longer than 255 px (and this applies to whatever specific number you can imagine).

**Comment by psifidotos** [comment]
>  I don't want to elide the application name if it is longer than 255 px

and what is going to happen if the application name is longer that 255px?

**Comment by kupiqu** [comment]
> Sounds good in terms of Maximum (I was surprised myself about previous behavior to this regard), but then we need a Minimum setting (that accounts for the full length of the applet). Following your example, I don't want to elide the application name if it is longer than 255 px (and this applies to whatever specific number you can imagine).

Let me try to explain myself better:

- length setting encodes `minimum length up to`
- before the commit: everything was consistent to this regard, also for maximum length, which represented `minimum length up to maximum available space`, which actually is `whatever the actual length is given external constraints`
- now maximum encodes differently, it represents `maximum available space always` and it is set in a static way, so the coherence of the length setting is broken (it means differently depending on the value taken).
- and the previous behavior is missing: `whatever the actual length is given external constraints`, this is not possible anymore

I would kindly recommend to inform the user about what the length setting really is, and make it as consistent as possible, although it may not be possible to achieve total consistency. If so, I would recommend a tooltip or explicit text around the setting to inform about the `up to px` of minimum length and other particular values, in contrast to maximum length (static length). I would also kindly recommend to add the minimum length option (i.e., actual size up to the maximum available space given the external constraints).

I hope I was clearer.

**Comment by kupiqu** [comment]
> > I don't want to elide the application name if it is longer than 255 px
> 
> and what is going to happen if the application name is longer that 255px?

let's say the available space is 1000px, maximum would occupy all of it (also for lengths < 1000px; I fail to understand why this is useful, but I'm sure there is a reason for it), minimum would occupy the actual length up to 1000px (then elide), and 255px would occupy the actual length up to 255px (then elide).

**Comment by psifidotos** [comment]
What is the current behavior with update Latte or you can test it with a plasma panel:

Option maximum: the applet occupies all the free space, if the window title exceeds that space then it is elided

Option specific size (e.g.300px) : if the window tile is shorter than 300px. then the applet has that space. e.g. 0-300px. The applet can not go above 300px. if the window title exceeds 300px. then it is elided.

**Comment by kupiqu** [comment]
> What is the current behavior with updated Latte or you can test it with a plasma panel:
> 
> Option maximum: the applet occupies all the free space, if the window title exceeds that space then it is elided
> 
> Option specific size (e.g.300px) : if the window tile is shorter than 300px. then the applet has that space. e.g. 0-300px. The applet can not go above 300px. if the window title exceeds 300px. then it is elided.

Yes, I know, that is what I explained in previous comment https://github.com/psifidotos/applet-window-title/issues/32#issuecomment-451662672, which I learned by trial and error (unfortunately, other users will need to do the same to learn about it too).

Why not adding an option minimum, which would account for previous option maximum before last commit? This would mean window title length up to available space, it it exceeds it, then it is elided.

**Comment by psifidotos** [comment]
What was the behavior of old maximum?

**Comment by trmdi** [comment]
I've found some issues:

1, When I set `Length = maximum`, in the edit-mode:
![image](https://user-images.githubusercontent.com/11857205/50727022-8f894900-1147-11e9-91f8-9704b4a757f4.png)
+ suggest: Latte panel's width should follow the value which users set in the settings, even in the edit-mode

2, You should change the text `Length` -> `Maximum length` and `maximum` -> `Fluid`, `Fill width/panel`,... I think it's easier to understand.
+ suggest: the default values should be: Application for Text style, the maximum number of the Length slider. Otherwise, the panel looks weird. For example:
![image](https://user-images.githubusercontent.com/11857205/50727316-d7aa6a80-114b-11e9-94a7-ab398ea9623c.png)

**Comment by psifidotos** [comment]
@trmdi @kupiqu #34
