### ISSUE TITLE
Improve default values and edit mode behavior

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/applet-window-title#34]

**Comment by kupiqu** [comment]
I don't completely understand the change, in particular the different behavior between Application vs. Aplication-Title when Maximum is set to e.g. 256 px.

**Comment by trmdi** [comment]
That's why the default value of Text style is Application.

**Comment by kupiqu** [comment]
> The default value of Text style is Application

It sounds good

> I think that is the best combination for the default values in most of the use cases.

I don't know if I understand you right... Do you mean that the default behavior when the window title is shown is (and should be) the filled in mode, irrespective of the length setting? If so, I disagree, it looks quite bad to me. I thought it was a bug to tell the truth

**Comment by kupiqu** [comment]
This is what I mean, under same length setting:

- Application
![image](https://user-images.githubusercontent.com/3875196/50728411-3396d400-10f7-11e9-8c89-30300c6d20e2.png)

- Application-Title
![image](https://user-images.githubusercontent.com/3875196/50728407-24178b00-10f7-11e9-87ff-ab6e4e4acd6a.png)

**Comment by psifidotos** [comment]
@kupiqu are you using Latte v0.8.4?

**Comment by kupiqu** [comment]
Yes

**Comment by trmdi** [comment]
No, the default is Text style = Application. and max-length = 1500. Try setting your config like that you will understand.

**Comment by kupiqu** [comment]
> No, the default is Text style = Application. and max-length = 1500. Try setting your config like that you will understand.

That is what I have and showed above, but I'm talking about Application-Title setting under same max-length. It may be fixed in Latte 0.8.5 and need to wait for it patiently...

**Comment by trmdi** [comment]
In the git version, it has no blank space like your screenshot. :)

**Comment by psifidotos** [comment]
> It may be fixed in Latte 0.8.5 and need to wait for it patiently...

the commit has been merged for upcoming 0.8.5 , Latte<=0.8.4 was behaving a little selectively to applets the fill width or height. From >= v0.8.5 Latte will try to behave the same with plasma panels by just improving only small glitches nothing more...

@kupiqu if you want to test it out you can add the window title applet in a plasma panel and play with it now with no need to wait...

If Latte behaves very strange for an applet when comparing that applet in a plasma panel then this is considered a bug for Latte from now on!

**Comment by kupiqu** [comment]
> > It may be fixed in Latte 0.8.5 and need to wait for it patiently...
> 
> the commit has been merged for upcoming 0.8.5 , Latte<=0.8.4 was behaving a little selectively to applets the fill width or height. From >= v0.8.5 Latte will try to behave the same with plasma panels by just improving only small glitches nothing more...
> 
> @kupiqu if you want to test it out you can add the window title applet in a plasma panel and play with it now with no need to wait...
> 
> If Latte behaves very strange for an applet when comparing that applet in a plasma panel then this is considered a bug for Latte from now on!

Sounds good. I'll keep using the Application style for now until v0.8.5 is released :)
