### ISSUE TITLE
The opacity transition part of the elided text should be longer.

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-title#35]
The length of the opacity transition part should be longer ? E.g currently the transition length = 2px -> new length = 5px...

See the difference:
![image](https://user-images.githubusercontent.com/11857205/50731000-b158ef00-118c-11e9-9a84-4d5cfe1ab775.png)

**Comment by psifidotos** [comment]
the applet does not have any  **opacity transition part**

**Comment by kupiqu** [comment]
> Eliding properly is not easy and KWin is doing fantastic job in its titlebar for this... you can read feature #27 that I like.
> 
> All eliding etc. I am fan of the KWin way, meaning that applet should prioritize its eliding, the upcoming commit is trying to do the following:
> 
> 1. Title is elided first not depending where it is shown, first or last
> 2. If [1] is not enough and the Application information still overlap then Title becomes hidden and Application name is elided

This sounds great

It seems though that @trmdi is referring to a linear gradient in the font color when eliding from its original color toward the background color, as seen in the second screenshot. It seems like a nice effect.

@trmdi where did you get the second screenshot from?

**Comment by trmdi** [comment]
@kupiqu
It's a gnome thing: https://www.omgubuntu.co.uk/2017/04/global-menu-for-gnome-extension-development

**Comment by kupiqu** [comment]
@psifidotos whenever you have some spare time, would you revisit https://github.com/psifidotos/applet-window-appmenu/issues/35? The screenshots in the original report here (global menu gnome extension vs applet-window-appmenu) reminded me about that. In gnome different menu entries seem to appear closer together.

[sorry in advance for the off-topic comment]
