### ISSUE TITLE
Application switching lags, causing temporary obscurement of text/overuse of space

### ISSUE THREAD

**Issue by Chromace** [psifidotos/applet-window-title#36]
As of the latest commit (9557c0e), switching between applications yields some lag. This comes in the form of a few seconds of adjusting its spacing. Sometimes the entire title won't be shown until a little while in, or the whole title might be shown, and the space it uses takes time to be reduced. This can be seen in the GIF image below.

![switching](https://user-images.githubusercontent.com/16624211/51808983-b0306300-22ef-11e9-93e4-5087d9177e3f.gif)

**Comment by Petross404** [comment]
I am noticing the same issue as well. Why is this re-opened? Is there a workaround?

**Comment by psifidotos** [comment]
No workaround... It is open until I am get bored of it or someone provides a solution until then

**Comment by Petross404** [comment]
> until I am get bored of it 
Well, are you yet?

**Comment by psifidotos** [comment]
No

**Comment by psifidotos** [comment]
BTW by using latest git version and latest master version such lag does not appear in my system...

so I will wait for community feedback if this is still valid...

**Comment by Chromace** [comment]
Currently using v0.4, the issue still appears to be present on my system.
[Recording.zip](https://github.com/psifidotos/applet-window-title/files/3029033/Recording.zip)

**Comment by psifidotos** [comment]
> Currently using v0.4, the issue still appears to be present on my system.
> [Recording.zip](https://github.com/psifidotos/applet-window-title/files/3029033/Recording.zip)

1. plama panel
2. OR Latte (which Latte version?)

**Comment by Chromace** [comment]
> > Currently using v0.4, the issue still appears to be present on my system.
> > [Recording.zip](https://github.com/psifidotos/applet-window-title/files/3029033/Recording.zip)
> 
>     1. plama panel
> 
>     2. OR Latte (which Latte version?)

Currently using Latte dock, version 0.8.7.

**Comment by Chromace** [comment]
> in that case there is a chance that this delay is from Latte...
> 
> with plasma panel how does it go, is it any better ?

I got some interesting results using Plasma's panel.

I disabled the "Show when available" option for icons, which resulted in a good deal of the application titles being hidden for many programs. Keeping it enabled made it the application title completely visible.

Unlike Latte dock, the space allocated for the application title is kept the same (overly large, as seen in the video), which probably a factor towards why there's no perceptible delay.

[Recording.zip](https://github.com/psifidotos/applet-window-title/files/3031523/Recording.zip)

**Comment by psifidotos** [comment]
> I disabled the "Show when available" option for icons, which resulted in a good deal of the application titles being hidden for many programs. Keeping it enabled made it the application title completely visible.

please open a new issue for this, including a screenshot of your settings window

**Comment by Chromace** [comment]
> > I disabled the "Show when available" option for icons, which resulted in a good deal of the application titles being hidden for many programs. Keeping it enabled made it the application title completely visible.
> 
> please open a new issue for this, including a screenshot of your settings window

All done! Should I create a new issue concerning the fact that the global menu widget isn't properly spaced up against the other applet?

**Comment by psifidotos** [comment]
yes, any different issue at its own thread with the info needed

**Comment by Chromace** [comment]
> yes, any different issue at its own thread with the info needed

There we go, issue #55 is reported.
