### ISSUE TITLE
spacing seems to be slightly inconsistent with substitutions

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-title#37]
![image](https://user-images.githubusercontent.com/3875196/52546061-4baee280-2d8a-11e9-9bef-cbbc69f7e66c.png)

![image](https://user-images.githubusercontent.com/3875196/52546074-7305af80-2d8a-11e9-8e83-aa2e21f9c889.png)

Other examples are gimp, dragon player, and others.

**Comment by psifidotos** [comment]
in case you have a way to reproduce feel free to reopen
