### ISSUE TITLE
spacing seems to be messed up in some applications

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-title#38]
In contrast to issue #37 this happens in some applications irrespective of substitutions

![image](https://user-images.githubusercontent.com/3875196/52546262-b90f4300-2d8b-11e9-9848-2a07951c3db1.png)

![image](https://user-images.githubusercontent.com/3875196/52546362-8154cb00-2d8c-11e9-9e4b-5271f68d05d4.png)

**Comment by kupiqu** [comment]
This is much larger for these applications compare to default spacing, e.g.:

![image](https://user-images.githubusercontent.com/3875196/52546431-1b1c7800-2d8d-11e9-8161-e269c2f5a39a.png)

**Comment by psifidotos** [comment]
Try to visually debug it please in order to identify which element triggers this.

What I am usually doing is I put as a child the following for each in question item:

```
Rectangle {
  anchors.fill: parent
  color: "transparent"
  border.width:1
  border.color: "red" //set that differently for each item
}
```

in order to identify who is responsible for this

**Comment by psifidotos** [comment]
in case you have a way to reproduce please reopen
