### ISSUE TITLE
Elided title even if there is free space at panel

### ISSUE THREAD

**Issue by IevgenSobko** [psifidotos/applet-window-title#39]
Elided title even if there is free space at panel

![2019-02-14__23-54-09](https://user-images.githubusercontent.com/14232100/52888142-37505880-3183-11e9-8d5e-8645dacbf62a.png)

Maximum already set to maximum value 1500

![2019-02-16__00-39-33](https://user-images.githubusercontent.com/14232100/52888191-6e266e80-3183-11e9-9165-fc9668ebb27c.png)

**Comment by psifidotos** [comment]
1. Plasma panel?
2. What are the settings of the global menu?

**Comment by IevgenSobko** [comment]
1. Yes it is plasma panel
2. Global menu has only 2 option to show full menu or show only icon. It is standard plasma global menu.
Here is structure of my panel. I'm using spacer to separate menu and tray
![2019-02-16__00-45-30](https://user-images.githubusercontent.com/14232100/52888483-78953800-3184-11e9-900d-c39109620c5d.png)

**Comment by psifidotos** [comment]
Makes sense, plasma panel can't support smart eliding like Latte panels. Probably an option is needed of minimum length or to disable eliding

**Comment by psifidotos** [comment]
I have to rethought this,

If you remove the panel spacer and enable for window title, fill available space, what is happening?

**Comment by IevgenSobko** [comment]
@psifidotos Title is displayed correctly, but global menu jumps way to far to tray plasmoid
![2019-02-28__10-00-53](https://user-images.githubusercontent.com/14232100/53550655-eb68c080-3b3f-11e9-9d54-de02ffab2bbb.png)

**Comment by psifidotos** [comment]
all this comes from the panel spacer... 

I can add an option in order for the title to be always visually presented without eliding and that would fix this, 

what do you think?

**Comment by IevgenSobko** [comment]
I think it is a good decision.
Even if the title is too long there is a possibility to manage substitutions and it will be possible to make it shorter.

**Comment by psifidotos** [comment]
@IevgenSobko there is a chance that I fixed it without an option for eliding, can you please confirm the fix?

**Comment by IevgenSobko** [comment]
@psifidotos I'll do that with the new release and installing from AUR repository.

**Comment by psifidotos** [comment]
@levgenSobko is that ok now?

**Comment by psifidotos** [comment]
> @psifidotos I'll do that with the new release and installing from AUR repository.

is that ok now?

**Comment by IevgenSobko** [comment]
I didn't notice this issue already for a few weeks even without your fix.
Maybe some fixes from KDE side.

**Comment by psifidotos** [comment]
Nice, it was totally on applet side, after version 0.4 you must be OK with it
