### ISSUE TITLE
Tooltip with window title?

### ISSUE THREAD

**Issue by rokups** [psifidotos/applet-window-title#4]
[plasma-active-application](https://github.com/kupiqu/plasma-active-application/) conveniently displays a tooltip with full window title when widget displays only application name. Option to do the same would be very convenient. That way we get a minimalistic look while maintaining ability to see window title of maximized windows without moving them.

P.S. Perfect applet, especially love the fact that widget also allows dragging it to move maximized borderless window. Also it works in sync with window buttons applet on multiscreen. Now we need to strong-arm global menu applet maintainer to implement same multiscreen support and hiding when window is not maximized. Thank you for all these great things made for plasma :heart:

**Comment by psifidotos** [comment]
> That way we get a minimalistic look while maintaining ability to see window title of maximized windows without moving them.

I will think it...

> Now we need to strong-arm global menu applet maintainer to implement same multiscreen support 

I have sent patches for this but they need to be reviewed from plasma devs...

**Comment by kupiqu** [comment]
I second this. Particularly useful for multiple windows of the same application, e.g., browsers.
