### ISSUE TITLE
The window title is not maximized without a visible application icon

### ISSUE THREAD

**Issue by gikari** [psifidotos/applet-window-title#41]
When the display of the application icon is disabled, the title is shrunk to the three dots and possibly some letters at the beginning, despite the fact that the panel has an available space on it. 

Without the icon:
![without_icon](https://user-images.githubusercontent.com/14205339/53442264-f9bcbc80-3a19-11e9-8433-9afc46cbd0f6.png)

However, if the the icon is enabled in the applet's settings, the correct width of the title is restored.
With the icon:
![with_icon](https://user-images.githubusercontent.com/14205339/53442262-f9bcbc80-3a19-11e9-9377-d06b0c019222.png)

The rest of the applet's settings:
![widget_settings](https://user-images.githubusercontent.com/14205339/53442318-1658f480-3a1a-11e9-925f-9f29622b8d28.png)

The panel is Latte's one, however this behavior is also reproduced on a plasma panel too .

**Comment by psifidotos** [comment]
feel free to reopen in case it is not fixed
