### ISSUE TITLE
Consider adding a CMakeLists.txt

### ISSUE THREAD

**Issue by Petross404** [psifidotos/applet-window-title#43]
Hi psifidotos, I am trying to install this with portage but I can't since it doesn't contain a cmakelists.txt. Instead of relying only on plasmapkg2, consider adding an install target for make to work with.

I can provide the patch if you inform me where the applet is supposed to be installed system-wide.

Thanks.

**Comment by Petross404** [comment]
I 've created a PR for this.

**Comment by psifidotos** [comment]
sorry the current structure must remain
