### ISSUE TITLE
Provide a seperator like AWC

### ISSUE THREAD

**Issue by Petross404** [psifidotos/applet-window-title#45]
I am talking about this 
![47236515-a650b700-d406-11e8-94f8-f91f49efbd1b](https://user-images.githubusercontent.com/18561627/53750065-84d20280-3eb1-11e9-8ae7-5fcaf2235b78.png)

Watch next to 2.10. Can you do this?

**Comment by psifidotos** [comment]
There will be a new separator applet to do this,
but I dont know if it will be able to be shown dynamically only when there is a AppMenu

**Comment by Petross404** [comment]
Well, one can configure this to be enabled unconditionally in the window-title.

**Comment by psifidotos** [comment]
> Well, one can configure this to be enabled unconditionally in the window-title.

why ? as long as there will be a separator applet? 

there is already one https://store.kde.org/p/998907/ but I am preparing a new one...
