### ISSUE TITLE
Are there any plans to unify window-title, window-appmenu and window-buttons?

### ISSUE THREAD

**Issue by Petross404** [psifidotos/applet-window-title#46]
Are there any plans for this? Wouldn't these 3 cooperate better if they were under the same package?

**Comment by psifidotos** [comment]
nope, there is no chance...

this is a design decision

**Comment by Petross404** [comment]
Does it provide better flexibility and/or customizability?

**Comment by psifidotos** [comment]
Suits me better from maintainability point of view

**Comment by Petross404** [comment]
Good point ;)
