### ISSUE TITLE
Application value is not very good with LibreOffice 6.2.1.2

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-title#47]
With LibreOffice 6.2.1.2, Application is "soffice.bin". Is there a more accurate way to get the Application value?

- applet-window-title:
![image](https://user-images.githubusercontent.com/11857205/54046669-a01d7480-4207-11e9-85f5-2ee41d54bbab.png)

- kwin:
![image](https://user-images.githubusercontent.com/11857205/54046735-ccd18c00-4207-11e9-9a7f-b948c9185f8d.png)

- Latte plasmoid tooltip:
![image](https://user-images.githubusercontent.com/11857205/54046937-58e3b380-4208-11e9-950a-6b3a53ffaf02.png)

**Comment by psifidotos** [comment]
this is totally upstream...
@trmdi xprop the libreoffice windows and you will see that for all the `WM_CLASS(string)` is set faulty to `soffice.bin` in the past/previous versions that was set to `libreoffice-writer`, libreoffice-calc etc... based on the application that was running...

more info at: https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F
