### ISSUE TITLE
Ability to Substitute "Default" 

### ISSUE THREAD

**Issue by TJBrown392** [psifidotos/applet-window-title#48]
A request I have it the ability to specify or substitute the text that shows up when you're focused on the desktop instead of an application. An example would be setting the text to my computer name, so in my case it would be "Noctowl" or "Nebby", or I could have the distro name there such as "Kubuntu" or "Fedora". 

Along with this request, the ability to set a custom icon that shows when you're focused on the desktop itself, such as the distro logo or whatever the user may wish. 

An example of a tool that already provides this functionality is Active Window Control.

**Comment by psifidotos** [comment]
The "Default" name and icon are just the current activity name and icon... Change the current Activity name and Icon from Activities Explorer to whatever you want and the window title applet will just use that one...
