### ISSUE TITLE
Need CMakeLists.txt for packaging

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-title#5]
It helps distros create the package for their users.
Btw, there is a small typo:
> Plasma 5 applet that **sShows** the application title and icon for active window

**Comment by psifidotos** [comment]
> It helps distros create the package for their users.

this is a qml-only plasma applet so I like the idea of users installing it through Widgets Explorer and Discover

**Comment by trmdi** [comment]
For example, they can create a meta that requires Latte-dock, applet-window-title, applet-window-button, create preinstalled Latte layout...

Users just need to install that meta package to get all the stuff. And updates are managed by the package manager. It's super convenient.
I have a feeling that Discover is still buggy. Personally I don't like using it.

Ok, thank you!

**Comment by psifidotos** [comment]
I will think it over
