### ISSUE TITLE
Window title misaligned when title exceeds char limit.

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-title#50]
Tested on version 4

![image](https://user-images.githubusercontent.com/45201036/55293919-61dd3480-5404-11e9-979c-4cf574486912.png)

This is with Chromium open to this site  https://github.com/psifidotos/applet-window-title

This happens when the title text exceeds the limit and is cropped off. If I use a higher characer limit, the title is aligned properly:
![image](https://user-images.githubusercontent.com/45201036/55293949-e62fb780-5404-11e9-9879-360c596b6dfe.png)

**Comment by psifidotos** [comment]
I will need:

1. your Latte layout file
2. which Latte version are you using?

**Comment by ripefig** [comment]
Not sure the version, I updated the whole thing from git a week ago.

Layout doesn't affect it. I created a simple layout to check this:

![image](https://user-images.githubusercontent.com/45201036/55294419-a5d33800-540a-11e9-8a6c-e33d08fe16ae.png)
(Chrome accessing KDE/Latte-Dock repo) Note that this issue can go away temporarily after you restart the dock, but eventually the problem always comes back)


[ActionPlugins][1]
RightButton;NoModifier=org.kde.latte.contextmenu

[Containments][1]
activityId=
byPassWM=false
dockWindowBehavior=true
enableKWinEdges=true
formfactor=2
immutability=1
isPreferredForShortcuts=false
lastScreen=-1
location=3
onPrimary=true
plugin=org.kde.latte.containment
raiseOnActivityChange=false
raiseOnDesktopChange=false
settingsComplexity=4
timerHide=700
timerShow=200
viewType=1
visibility=0
wallpaperplugin=org.kde.image

[Containments][1][Applets][2][Configuration][General]
isInLatteDock=true
launchers59=applications:firefox.desktop,applications:org.kde.dolphin.desktop

[Containments][1][Applets][228]
immutability=1
plugin=org.kde.windowtitle

[Containments][1][Applets][228][Configuration][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][Applets][228][Configuration][General]
containmentType=Latte
maximumLength=1034
style=ApplicationTitle

[Containments][1][Applets][3]
immutability=1
plugin=org.kde.plasma.analogclock

[Containments][1][ConfigDialog]
DialogHeight=1034
DialogWidth=522

[Containments][1][General]
advanced=false
animationLauncherBouncing=false
animationWindowAddedInGroup=false
animationWindowInAttention=false
appletOrder=228;3
panelPosition=10
panelSize=100
plasmaBackgroundForPopups=true
shadowOpacity=60
shadowSize=45
shadows=None
showGlow=false
splitterPosition=0
splitterPosition2=2
zoomLevel=0

[LayoutSettings]
activities=
background=
color=blue
disableBordersForMaximizedWindows=false
lastUsedActivity=
launchers=
preferredForShortcutsTouched=false
showInMenu=true
textColor=fcfcfc
version=2

**Comment by psifidotos** [comment]
this is how is shown in my system:

![image](https://user-images.githubusercontent.com/2216474/55335573-fc408500-54a3-11e9-9db4-d9281231b17e.png)

**Comment by ripefig** [comment]
You need to keep using it to observe it. You may not be able to obseve this at first launch. For example, the title of this page is fine right now:

![image](https://user-images.githubusercontent.com/45201036/55335821-825ccb80-54a4-11e9-930f-fb3ec9e14a53.png)

But after I go to another window and back, it will slide down. 

It happens about 70% of time, but not 100%. You should be able to see pretty soon, if you use Window title on your system.

What system are you using BTW? I am on Kubuntu 18.10

**Comment by psifidotos** [comment]
> It happens about 70% of time, but not 100%. You should be able to see pretty soon, if you use Window title on your system.

I am using Window Title in my system always but I have never see that behavior. I am not saying is not happening BUT I dont know how to reproduce in my system.

I am using Tumbleweed but I dont think this is relevant

**Comment by StarrKiss** [comment]
This happens to me also, no clue as to the cause. 
![image](https://user-images.githubusercontent.com/13007697/59080016-31a28e00-88ac-11e9-9f34-c9ed17688312.png)

**Comment by ripefig** [comment]
Happy to report that this is no longer an issue on Kubuntu 19.04.

**Comment by StarrKiss** [comment]
Well, shame, because I am still running 18.10 and it would be a pain to switch over.

**Comment by psifidotos** [comment]
@ripefig probably a Qt issue then

**Comment by StarrKiss** [comment]
Would there be any way to work it down into 18.10 so I dont have to have this?

**Comment by psifidotos** [comment]
No idea, because in my system it does not occur

**Comment by StarrKiss** [comment]
Ok, lets try and troubleshoot, to see what the problem is.
