### ISSUE TITLE
Request: Click-activated expose_ actions

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/applet-window-title#52]
This request is to add configuration options to invoke a any/all of the following kwin actions when clicking the applet:

```bash
qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Expose"
qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"
qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeClass"
qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ShowDesktopGrid"
```

As far as I can tell, while double-click is already used for maximize/restore, nothing is assigned to single-click.

**Comment by psifidotos** [comment]
Sorry I don't agree... Too much weight for a simple applet... All of them can be trigerred with KWin hot corners
