### ISSUE TITLE
Window titles are not shown when icons are disabled + using Plasma's panel

### ISSUE THREAD

**Issue by Chromace** [psifidotos/applet-window-title#54]
A reference to #36 , having uncovered this error. By disabling the applet's option to show an icon alongside the window title, the entire title is not shown while using Plasma's panel. This error is not seen using Latte dock.

With icon disabled:
![Screen 1](https://user-images.githubusercontent.com/16624211/55381537-201ccd00-556f-11e9-8b5b-6ec20ba53f85.png)
![Screen 2](https://user-images.githubusercontent.com/16624211/55381538-201ccd00-556f-11e9-8790-4dee898978dc.png)

With icon enabled:
![Screen 3](https://user-images.githubusercontent.com/16624211/55381548-24e18100-556f-11e9-8713-d37a9af7c03b.png)
![Screen 4](https://user-images.githubusercontent.com/16624211/55381550-24e18100-556f-11e9-950b-4a0382885e4e.png)

**Comment by psifidotos** [comment]
it works just fine, add a panel spacer at the right of global menu
