### ISSUE TITLE
Applet does not expand/contract with text size using Plasma's panel

### ISSUE THREAD

**Issue by Chromace** [psifidotos/applet-window-title#55]
Using Plasma's panel along with this applet creates uneven amounts of space, shifting other widgets aside. This can be clearly seen in the screenshot below:
![Screen 2](https://user-images.githubusercontent.com/16624211/55385557-2a43c900-5579-11e9-9441-1a18ac4dfa35.png)

Ideally, such space would be flexible, taking up only as much as needed, similar to the behaviour under Latte dock.

**Comment by psifidotos** [comment]
show me your settings window please

**Comment by psifidotos** [comment]
it works just fine, add a panel spacer at the right of global menu
