### ISSUE TITLE
Center the window title

### ISSUE THREAD

**Issue by rkunschke** [psifidotos/applet-window-title#56]
I think this would be a great Option in some cases. 
![image](https://user-images.githubusercontent.com/29981387/56737779-7a264200-676b-11e9-816c-61b44269482f.png)

**Comment by psifidotos** [comment]
Use a Latte panel and add the applet in the center of Justify mode

**Comment by rkunschke** [comment]
That is what i did. But it seems like the justify splitters is centering the applet in the middle of the panel and not in the middle of the free space. In normal cases where the window title is not so long it works good for me. Its not a big deal. 
![image](https://user-images.githubusercontent.com/29981387/56749776-af8a5a00-6782-11e9-86b7-ce3f286b3e59.png)

**Comment by psifidotos** [comment]
Yep this is right Justify alignment centers the applet in the exact center of the panel
