### ISSUE TITLE
Tooltip doesn't show window title

### ISSUE THREAD

**Issue by Nilsolm** [psifidotos/applet-window-title#58]
From what I gather, the applet is supposed to show the full window title in a tooltip if you hover the mouse pointer over it. However, the tooltip will always just say "Window Title" as seen in the screenshot below.

![lattebug2](https://user-images.githubusercontent.com/22319656/56813463-44ea2480-683d-11e9-9767-fcece7de050e.png)

System info:

OS: Kubuntu 19.04
Plasma version: 5.15.4
Frameworks version: 5.56.0
Qt version: 5.12.2
Latte-dock version: 0.8.8 (installed from Ubuntu repository)
Window Title Applet version: 0.4

I did some testing and apparently, the issue seems to have been introduced with the 0.4 version of the applet. I tried version 0.3 and it works as expected.

**Comment by psifidotos** [comment]
Lock the window title applet from Latte

**Comment by Nilsolm** [comment]
You mean from the Dock/Panel Settings view? That doesn't appear to do it. If I lock the applet, then no tooltip will show at all.

I also tried completely nuking and reinstalling Latte, but that doesn't seem to fix it either. Could it be maybe some issue with the latte-dock package in the Ubuntu repositories? I could try building Latte from git later today to see if it works that way.

**Comment by psifidotos** [comment]
Just checked the code, you are right the tooltip is broken for with Latte v0.8 version if you have not enabled the double click to maximize restore active window it should work but it does not.

Either you wait for a fix in next version or you can try Latte git version for which you won't have that issue

**Comment by Nilsolm** [comment]
Aye, I did just try it with the newer version from Rik Mills' PPA and it worked properly.

Thanks for the info. It's not a big issue, I can live with it until the next version is out.
