### ISSUE TITLE
Applet maximum width seems bigger when no icon is present 

### ISSUE THREAD

**Issue by gmsanchez** [psifidotos/applet-window-title#59]
Hi, I have configured Window Title applet to have a maximum width of 300 px and I have AppMenu on the right side of Window Title. If I choose not to use the application icon (the way I would like to use it), there seems to be a lot of unused space at the right. I attach some screenshots in order to see the difference in spacing. The only change between screenshots was to enable the application icon.

![Screenshot_20190611_233513_crop](https://user-images.githubusercontent.com/2853668/59319796-5333b900-8ca2-11e9-8e86-da6797bf458d.png)
![Screenshot_20190611_233534_crop](https://user-images.githubusercontent.com/2853668/59319797-575fd680-8ca2-11e9-9b17-ea60c044038b.png)

**Comment by psifidotos** [comment]
1. Latte or panel
2. If Latte can you send the layout file?
3. Show me a screenshot for the settings of AppMenu

**Comment by gmsanchez** [comment]
1. I am using Latte for the upper panel and I a lower dock that auto hides.
2. The layout file is attached.
[latte_layout.layout.latte.txt](https://github.com/psifidotos/applet-window-title/files/3281778/latte_layout.layout.latte.txt)
3. Here goes the screenshot
![Screenshot_20190612_112731](https://user-images.githubusercontent.com/2853668/59359904-96734380-8d05-11e9-92fe-24a1edaee849.png)
.
