### ISSUE TITLE
Double click to maximize doesn't work

### ISSUE THREAD

**Issue by princenna** [psifidotos/applet-window-title#60]
Used this applet with the previous version of latte-dock-git and it worked fine but I ran into some problems with latte and totally uninstalled it along with the applet and since then double-clicking on the applet does nothing.
![deepin-screen-recorder_Select area_20190613231146](https://user-images.githubusercontent.com/46909812/59470782-bb180a00-8e30-11e9-9a48-16625221e9c6.gif)

**Comment by psifidotos** [comment]
Have you enabled in Latte, Behavior page the drag and maximize/restore option?

**Comment by princenna** [comment]
Wow it worked, had no idea, will do proper research next time.
