### ISSUE TITLE
Extreme padding when it goes over char limit

### ISSUE THREAD

**Issue by StarrKiss** [psifidotos/applet-window-title#63]
![image](https://user-images.githubusercontent.com/13007697/59971820-5e5fd200-9549-11e9-85f6-1023c19d2a41.png)

The padding on the right side is far too large when the characters exceed their limit. This is on Manjaro 18.

**Comment by psifidotos** [comment]
Is that plasma panel?

**Comment by psifidotos** [comment]
If this is plasma panel you need to add a panel spacer

**Comment by StarrKiss** [comment]
This is a latte dock panel.

**Comment by StarrKiss** [comment]
NOT a plasma panel

**Comment by trmdi** [comment]
You should send your latte layout.

**Comment by psifidotos** [comment]
What is your Latte version?

**Comment by StarrKiss** [comment]
Latest, built from git

**Comment by psifidotos** [comment]
Has never occured in my system

1. Send your layout
2. and steps to reproduce afterwards
