### ISSUE TITLE
LastActiveWindow does not work for this applet?

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-title#64]
It works for the `appmenu` applet, but not for this one:

![image](https://user-images.githubusercontent.com/11857205/60005949-b3aaf900-9699-11e9-894e-72003ae02a99.png)

**Comment by psifidotos** [comment]
1. Are you using latest git versions for both Latte  and applets?
2. Latte-dock -d --with-window how many applets are requesting windows tracking in the end of debug window?

**Comment by trmdi** [comment]
1. Yes
2. how many applets are requesting windows tracking: 3

**Comment by psifidotos** [comment]
Send me also your layout to check it out in my system

**Comment by trmdi** [comment]
Please remove the ".txt" in the filename.
[trmdi.layout.latte.txt](https://github.com/psifidotos/applet-window-title/files/3320583/trmdi.layout.latte.txt)

**Comment by psifidotos** [comment]
should be fixed with: https://cgit.kde.org/latte-dock.git/commit/?id=67e9bd610ff2c4197b4b23247b21fb685ad382f2

all window applets broke from yesterday Latte commit
good catch!
