### ISSUE TITLE
Not working with flatpak applications

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [psifidotos/applet-window-title#65]
I tried many applications and the applet didn't show the title or any thing
here is an example (musescore) - flatpak
![f](https://user-images.githubusercontent.com/37955014/60620547-ca5cf880-9ddb-11e9-81cd-ce241ff5301e.png)

**Comment by psifidotos** [comment]
Are you using Latte or Plasma panel?

**Comment by psifidotos** [comment]
1. For Plasma Panel, you can forward this to plasma libtaskmanager issue IF you add a default plasma panel and the window previews do not show the window title properly
2. For Latte Panel/Docks, this is already fixed in git version upcoming v0.9

**Comment by ahmed-h-ayyad** [comment]
I am using latte 
how can I install git version?

**Comment by psifidotos** [comment]
1. either you get for v0.9 release
2. or you build yourself
3. or you ask at your distro packagers if they provide it
