### ISSUE TITLE
Godot Editor windows titles get cut off

### ISSUE THREAD

**Issue by dpalacio** [psifidotos/applet-window-title#66]
## What is Godot
Godot is an open source game engine for 2D and 3D games. It comes with a project manager and editor for developing.

## Applet Window Title Issue
When a Godot window first appears it's often the case that the title displayed in the applet is padded and cut off in the middle.
![image](https://user-images.githubusercontent.com/12900/61172483-a53e5780-a54a-11e9-85d2-2411c4a8f113.png)
Once the focused window is switched off to another and back the window title is not as cut off anymore but still misses content.
![image](https://user-images.githubusercontent.com/12900/61172533-678dfe80-a54b-11e9-9781-3a6efa5bcd55.png)

## How to reproduce
1. Install Godot. The editor is probably available in your distribution. It is packaged in Debian as `godot3`.
2. Open the editor. At this point the window title should already be cut.
![image](https://user-images.githubusercontent.com/12900/61172575-c3f11e00-a54b-11e9-82af-6e9fcf323220.png)
3. Create a new project. Once again, the title should be cut when the new window appears.

## System Information
OS: Debian Buster (stable)
libkf5plasma5: 5.54.0
plasma-desktop: 5.14.5.1
kwin-x11: 5.14.5
Applet version: 0.5.0
Godot version: 3.0.6 and git master
Running on Xorg

**Comment by psifidotos** [comment]
is that a plasma panel?

**Comment by psifidotos** [comment]
As a first step you need to fix the godot desktop file, you can follow: https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F

**Comment by dpalacio** [comment]
Yes, it's a plasma panel. Setting the StartupWMClass helps if the .desktop file is under a `share/applications` folder. I guess it must be entered into the sycoca database.

While I'm satisfied now, is there a reason the last bit with the document name is missing?
![image](https://user-images.githubusercontent.com/12900/61173329-83979d00-a557-11e9-8e99-c73041b4c190.png)
Also, the application name is duplicated but that is Godot's fault and mine.

**Comment by psifidotos** [comment]
I have fixed it with the last commit, it should work even with StartupWMClass or NOT

what I do for the faulty desktop files in my system is the following:

1. I copy paste them from `/usr/share/applications` to `~/.local/share/applications`
2. I add the `StartupWMClass`record in the desktop file in `~/.local/share/applications`
3. This way the record is not deleted ffter updating the relevant application
