### ISSUE TITLE
Layout breaks with very long window titles

### ISSUE THREAD

**Issue by dpalacio** [psifidotos/applet-window-title#67]
The window title applet layout breaks with very long window titles.
![image](https://user-images.githubusercontent.com/12900/61190983-69021880-a66a-11e9-9ae8-584071ecb01d.png)

The panel is a latte-dock panel.
Applet version is 0.5.0

Web page with long window title: https://twitter.com/TimSweeneyEpic/status/1142566747289083906

**Comment by psifidotos** [comment]
Send me also your layout file

**Comment by dpalacio** [comment]
[broken-long-title.layout.latte.zip](https://github.com/psifidotos/applet-window-title/files/3392440/broken-long-title.layout.latte.zip)

**Comment by dpalacio** [comment]
How is it going? I ask because I'd like to know if I should add a bug report on latte-dock. The top latte-dock panel I sent in that layout also breaks on very long window titles. It becomes string-like thin and is almost invisible. Is that known? Should I make a report about that?

**Comment by psifidotos** [comment]
What is your Latte version?

**Comment by dpalacio** [comment]
Latte git master (2d8f2981be43a981c2fb195495ab6904a7845f1c)

**Comment by psifidotos** [comment]
enable "Fill available space" from applet settings

**Comment by dpalacio** [comment]
Thanks, that fixes my major gripe. The window title widget's own layout still breaks as shown in the original report, though I can live with it.

**Comment by psifidotos** [comment]
> The window title widget's own layout still breaks as shown in the original report, though I can live with it.

unfortunately I havent managed to ever reproduce this in my system..
please open a new bug report just for this, in order to keep track of the issue
