### ISSUE TITLE
Window Title applet is updated sometimes and not others.

### ISSUE THREAD

**Issue by Petross404** [psifidotos/applet-window-title#68]
@psifidotos As I [pointed](https://www.reddit.com/r/kde/comments/cua6sv/inconsistency_with_lattes_window_title_applet/) out title applet isn't updated when an application is closed, nor when it looses focus to another window or desktop. It updates (correctly) only when an app is minimized.

correct:
![osiwuxfha5i31](https://user-images.githubusercontent.com/18561627/63600694-b4dea080-c5cc-11e9-9912-95bbb0cb6c2f.png)
 probably not so correct:
![slszyqzka5i31](https://user-images.githubusercontent.com/18561627/63600735-cb84f780-c5cc-11e9-9302-73951227e48a.png)

At this point Dolphin is closed. Shouldn't the applet print the name of the activity or whatever the user wants it to print as default?

**Comment by psifidotos** [comment]
1. Are you using latest version?
2. Plasma or Latte panel?

**Comment by psifidotos** [comment]
3. Which Plasma or Latte version are you using?
4. I dont understand your comment "loses focus for another window" isnt in that case prints the the new window title?
5. When a window changes to another desktop the title is still stuck like in your screenshots?

**Comment by Petross404** [comment]
1) I am using version 0.9.1 from the gentoo repo
2) I am using Latte
3) Plasma 5.16.4
4) My bad, what I mean is that it looses focus for desktop. Also I was wrong about minimising the app, as neither this updates the applet to print "Activity foo" or "Default" 
5) Yes, for example moving falkon to Desktop 2 doesn't update the applet.

**Comment by psifidotos** [comment]
Can you show me a screenshot of plasma systemsettings, Screens, Compositor page?

**Comment by Petross404** [comment]
Will do ASAP in the morning. Thanks.

**Comment by psifidotos** [comment]
You probably have enabled Previews for all windows and that creates the problem you are mentioning.

For desktop to not show the activity details in favor of the last active window even if that is not active, this is a feature request and you can open a different thread. The current behavior of showing activity details when the desktop is active, is intentional

**Comment by Petross404** [comment]
Compositor:
![Screenshot_20190824_103536](https://user-images.githubusercontent.com/18561627/63634149-30872e80-c65b-11e9-8210-b49cab87878c.png)
Screens:
![Screenshot_20190824_103604](https://user-images.githubusercontent.com/18561627/63634152-33821f00-c65b-11e9-83a5-41bef73794ef.png)
I have one 19" screen for the moment, so no fancy setup.

> You probably have enabled Previews for all windows and that creates the problem you are mentioning.

I don't know if it makes any difference but the specific dock is configured as "Panel" and I can't find an option about "Preview for all windows."

**Comment by psifidotos** [comment]
I checked it out it is ok from Compositor screenshot.

1. How did you install the applet?
2. You can send your Latte layout file to check it out in my system. Until now I haven't been able to reproduce any of the issues you are describing

**Comment by Petross404** [comment]
1. I installed it from Get New Widgets.
2. I don't know exactly which file is, so you can look from this [link](https://drive.google.com/open?id=1ugc1Ep3B9Sz4shzT5Xct0Rkh1WleKrpf) on my drive. It's the whole ~/.config/latte directory.

**Comment by psifidotos** [comment]
If you right click on your panel->Layouts which one in bolded as current?

**Comment by psifidotos** [comment]
2. Can you also make a video demonstrating the issue and upload it in Google drive or dropbox? Not YouTube. Make sure that you first start Latte with: latte-dock -d --with-window

and you have scrolled the debug window at the far bottom that gives the details for the last active window used per screen

**Comment by Petross404** [comment]
1) Layouts > **My Layout**
2) Do you want to post here the link or should I mail it to you?

**Comment by psifidotos** [comment]
2. Yep, you can post the link here

**Comment by Petross404** [comment]
https://drive.google.com/open?id=1YeTSbtBzunHlYcGoL1lr3emktMJzHgg1

**Comment by Petross404** [comment]
Now that I uploaded to gdrive it's quality is not good. Let me know if I have to record again or send it to you with another way.

**Comment by psifidotos** [comment]
@Petross404 your installation is messed up. Please show me a screenshot from folder:

`~/.local/share/plasma/plasmoids/`

**Comment by psifidotos** [comment]
and also a screenshot of folder: 

`/usr/share/plasma/plasmoids/`

**Comment by Petross404** [comment]
http://dpaste.com/2PVB5RY -> system wide plasmoids
http://dpaste.com/354T3EM -> user installed plasmoids

**Comment by psifidotos** [comment]
@Petross404 ok... the gentoo installation for the window title applet has messed up your system. The Gentoo installation has named the applet org.kde.windowTitle instead of org.kde.windowtitle. So to use the original applet that you installed lately from widgets explorer you must do the following:

1. REMOVE the window title applet from your top bar. It is the faulty one!
2. REMOVE the windowTitle gentoo installation which you are currently using. If you remove it properly then the folder `/usr/share/plasma/plasmoids/org.kde.windowTitle`  should NOT exist afterwards.
3. Restart plasma
4. Drag n' drop the window title applet from Widgets Explorer to your top panel. Only one window Title should appear now in Widgets Explorer. You currently have two and they are different.

After you do [1-4]  then report back if anything works ok... Currently the gentoo installed window title applet is messing up your experience.

**Comment by Petross404** [comment]
Hmm, I unistalled it before I download the new form New Widgets. Portage might me responsible although I can't possibly imagine how. Anyway, I will report later ;)

**Comment by trmdi** [comment]
Try removing the cache in ~/.cache ?

**Comment by Petross404** [comment]
> Try removing the cache in ~/.cache ?

The directory that psifidotos mentioned still existed so I guess it has nothing to do with cache, although it doesn't hurt if I clear it. I can't figure out why this happened, my ebuild installed some files and portage certainly knows which files to remove when one uninstalls.

![Screenshot_20190825_163954](https://user-images.githubusercontent.com/18561627/63650813-6b6e8c80-c757-11e9-9f7d-78c5ec3f683e.png)

![Screenshot_20190825_164014](https://user-images.githubusercontent.com/18561627/63650815-72959a80-c757-11e9-89fd-5d44db90de86.png)

Psifidotos was right, indeed _this_ is the correct applet which works out of the box. Thank you both for helping with this.
