### ISSUE TITLE
Titles of Qt applications written in Python are "Python3"

### ISSUE THREAD

**Issue by krisives** [psifidotos/applet-window-title#69]
I believe every Python Qt application I have used with this applet has shown as `Python3` in the window titles. I even made a small test case where PyQt is used and confirmed that the application name is set correctly, but it still appears as `Python3` in this applet.

Is this a bug in KDE or this applet?

Thank you for your hard work.

**Comment by psifidotos** [comment]
Can you give me an example of such application to test in my system?

**Comment by krisives** [comment]
Sure, here is one: https://electroncash.org/ (it's a Bitcoin Cash wallet, note that it won't download a blockchain or anything, so it's easy to test with)

It's worth mentioning I have tried creating .desktop launchers and it doesn't seem to help.

Also, Java programs don't seem to be affected by this problem, such as Eclipse.

Here is a minimal example Python program that does it:

```
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot

def window():
    # This is supposed to make the change
    QApplication.setApplicationName('TestApp')
    app = QApplication(sys.argv)
    widget = QWidget()

    textLabel = QLabel(widget)
    textLabel.setText("Hello World!")
    textLabel.move(110,85)

    widget.setGeometry(50,50,320,200)
    widget.setWindowTitle("PyQt5 Example")
    widget.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
   window()
```

**Comment by psifidotos** [comment]
You need to create a desktop file that is going to contains the following:
`StartupWMClass=electron-cash`

afterwards in the desktop file you can assign any application name and icon you want.

This is all explained at: https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F

**Comment by krisives** [comment]
Thank you for the help.
