### ISSUE TITLE
Allow for end user fine-tuned title replacements

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-title#7]
There are a few reasons for why end user fine-tuned title replacements are important:

- style preference for minimalistic names
- style preference enhancing system coherence (MATLAB --> Matlab), avoiding redundant or already known information (Firefox web browser, Chromium web browser), or pretty much useless for many users (Gimp-2.10; unless a user has a system with Gimp-2.8 and Gimp-2.10, there is no much benefit; Telegram Desktop, desktop... what else could it be?)
- available space in horizontal panel is limited (global menu of certain apps is long + system tray + other applets like weather + user switch + buttons + etc). Web browser names are particularly long for, arguably, no reason
- AppName bugs, e.g., Back In Time at the moment which displays python3 instead of proper name. I reported and sent a pull request to fix this but it is still under processing, and will take a while until this is release, having fine-tuning replacements workarounds the issue until then.

My examples summary (other users may have others):

Firefox web browser --> Firefox
Chromium web browser --> Chromium
Google Chrome --> Chrome
Gimp-2.10 --> Gimp
Telegram Desktop --> Telegram
MATLAB --> Matlab

I have this implemented in a very minimalistic function in https://github.com/kupiqu/plasma-active-application.

If implemented, it seems you prefer not having the replacements in the window settings but in the config file. This is the missing component that would need adjustment.

**Comment by psifidotos** [comment]
I dont have any problem to add this but hidden from the simple user. It means that the user should be able to access that functionality on purpose.

How this can be set:

1. In the applet qml files by specifying one or two Array(s) in order to contain these information
 -- Cons:  in that case if the user installs the applet globally then he should have root privilege in order to update these Array(s) and with each update the information will be lost

2. In the applets configuration file.
 -- Cons:  in that case the user should access the plasmaappletsrc file, locate the settings of that applet and add in that settings the needed information. For Latte the same thing must happen but for .layout.latte files

3. [2] but provide an elegant and intelligent way to access a ui in settings for this

@kupiqu what is your opinion?

 [2] is easy and could be a start... but for [3] I will need something beautiful or if it does not look nice to be hidden from the user somehow...

**Comment by kupiqu** [comment]
Some on how to do it here:  https://github.com/kupiqu/plasma-active-application/issues/1

Function:

```
function fineTuning(title) {

        var replacements = plasmoid.configuration.titleReplacements;

        replacements = replacements.replace(/\n/g, ";");
        replacements = replacements.replace(/;;/g, ";");
        replacements = replacements.replace(/; | ;/g, ";");
        replacements = replacements.replace(/, | ,/g, ",");

        var appReplacements = replacements.split(";");

        for (var iReplacement = 0; iReplacement < appReplacements.length; iReplacement++){

            if (appReplacements[iReplacement].length > 0) {

                appReplacements[iReplacement] = appReplacements[iReplacement].replace(/"/g, "");

                var repText = appReplacements[iReplacement].split(",");

                var regEx = new RegExp(repText[0], "ig"); //case insensitive
                title = title.replace(regEx,repText[1]);
            }

        }
        return title;
    }
```

**Comment by kupiqu** [comment]
> [2] is easy and could be a start... but for [3] I will need something beautiful or if it does not look nice to be hidden from the user somehow...

I prefer a nice way [3] (the way I did is not nice) but let's start with [2] for now if you like...

**Comment by psifidotos** [comment]
why regular expressions? is this needed?

**Comment by trmdi** [comment]
IMHO you could create a new Config tab, like SystemTray: Config General, Config Entries. In that new tab, you show a table that has columns like "Match", "Replacement". The input value should be Regexp.

**Comment by psifidotos** [comment]
> The input value should be Regexp.

why?

**Comment by trmdi** [comment]
Because it's powerful for string substitutions.

**Comment by kupiqu** [comment]
I'm in a hurry so I cannot develop this much now, but:

Regexp are convenient, so you don't have to write so many replacements

Examples: 

- Gimp-2.8 vs. Gimp-2.10 vs. future releases

- Firefox web browser vs. Navegador web Firefox (ie, language independent)

- LibreOffice Calc, LibreOffice Writer, ... can all be replaced by the specific app, or the generic in one shot

etc etc

**Comment by trmdi** [comment]
If you worry about the performance reduction, you could disable that tab by default.

**Comment by psifidotos** [comment]
My main concern is how this will look nice to the user...

**Comment by kupiqu** [comment]
I think @trmdi had a great idea about having a table similar to what the weather applet ( https://github.com/kotelnik/plasma-applet-weather-widget) does.

**Comment by kupiqu** [comment]
Also, this could appear only under enabling advanced options, perhaps?

**Comment by kupiqu** [comment]
Ok, I am sure you will find the best way for it

**Comment by psifidotos** [comment]
I tried to simplify it a lot... the regexps code is at:  https://github.com/psifidotos/applet-window-title/blob/master/contents/tools/Tools.js

I cant test regular expressions because I dont know much... please test and report back...
strings in lists should be between ""

![default](https://user-images.githubusercontent.com/2216474/48439405-df264680-e78e-11e8-852d-51b049285ebf.png)

**Comment by kupiqu** [comment]
It works great, thank you!

**Comment by trmdi** [comment]
Why not a table? It could look better.

**Comment by psifidotos** [comment]
> It could look better.

not in my opinion... it would look heavy loaded...
feel free to provide mockups of course...

**Comment by kupiqu** [comment]
Mmm... beauty is in the eyes, I guess :)

**Comment by kupiqu** [comment]
Anyways, it's fine for me either way. the priority is the functionality behind :)

**Comment by trmdi** [comment]
> not in my opinion... it would look heavy loaded...
> feel free to provide mockups of course...

How about this?
![image](https://user-images.githubusercontent.com/11857205/48459469-dbc9a400-e7fc-11e8-98d6-2ad5c15b9602.png)

**Comment by psifidotos** [comment]
I don't like the actions in the end of the row and I would like to see how you imagine the Add to be done

**Comment by psifidotos** [comment]
Things for improvement:

1. Replace - with trash icon for removal action
2. Remove the actions for each row
3. + for ADD and trash for REMOVE under the bottom right corner of the table
4. Header titles centered
5. all valid texts are placed inside ""

**Comment by psifidotos** [comment]
6. Where the warnings will be shown?

**Comment by psifidotos** [comment]
I would like also someone to tell me the benefits between the current and the proposed ui

**Comment by trmdi** [comment]
1. If you place the Remove button in each Replace cell, users would think that button only clears that cell.
2. Buttons in the Action column shows that the button actions are applied to the whole row.
3. The Add button should be in the last row (line 3 in the picture) according to the Fitts's Law I've learned from you.
4. It should align with other cells.
5. "" is not necessary.
6. I don't think it is needed too. You would only add the new record only if both columns are not empty.

**Comment by trmdi** [comment]
> I would like also someone to tell me the benefits between the current and the proposed ui

It looks more professional. It shows the relationship between Match and Replacement value in each row.

**Comment by psifidotos** [comment]
@trmdi even though I believe there will be many issues with your proposal,
you can provide a pull request to test what you have in your mind and discuss in the pull request each and every one contradiction...

**Comment by trmdi** [comment]
A mockup with the Add button. But I think I should stop here, because this is not the main feature of the applet. And the current UI is good enough. You were right. There is no noticeable benefit from this.

![image](https://user-images.githubusercontent.com/11857205/48500667-fe47d580-e86d-11e8-8964-249a034e9906.png)

**Comment by kupiqu** [comment]
Off topic: please correct the typo: `Manage substitutions...` (note the missing `b`)

**Comment by kupiqu** [comment]
Also, upgrading the applet (or perhaps this was after restart my system, not sure) deleted all my substitutions. Is there a way to prevent this to happen?

**Comment by psifidotos** [comment]
> Also, upgrading the applet (or perhaps this was after restarting my system, not sure) deleted all my substitutions.

I changed the string names in the xml file... It shouldnt happen again.

**Comment by psifidotos** [comment]
> A mockup with the Add button. But I think I should stop here, because this is not the main feature of the applet. And the current UI is good enough. You were right. There is no noticeable benefit from this.

ok, no problem

**Comment by kupiqu** [comment]
> I changed the string names in the xml file... It shouldnt happen again.

Thank you
