### ISSUE TITLE
The bold font is looking differently from what it should

### ISSUE THREAD

**Issue by gikari** [psifidotos/applet-window-title#70]
I'm using the applet with Latte's panels. If I set the option to use bold font instead of Regular one, the new font looks like it has small letter-spacing (therefore making it unreadable sometimes), What's more is that it looks different from what bold variation of that font actually is.

Here is a couple of examples. The font on top is what the applet uses, the one below it is the bold variation of that font grabbed from the Plasma System Settings font preview.

**Inter font family.**
General font is set to "Inter 11 Medium". Expected bold font to be used as window title is "Inter 11 Bold". There it might be unclear, but fonts have a different width if checked pixel by pixel.
![image](https://user-images.githubusercontent.com/14205339/64910510-b8b29e00-d706-11e9-9a09-a17e25e96f23.png)

**San Francisco family.** 
General font is set to "SF Display Pro 11 Regular". Expected bold font is "SF Display Pro 11 Bold"
![image](https://user-images.githubusercontent.com/14205339/64910492-915bd100-d706-11e9-98eb-9e8e95996c93.png)

**Noto Sans family.**
Generel font is set to "Noto Sans 11 Regular". Expected bold font is "Noto Sans 11 Bold"
![image](https://user-images.githubusercontent.com/14205339/64910601-ae44d400-d707-11e9-9e6b-6e9d9f8a9dc5.png)

In fact there are fonts with more, that Bold, Italic and Bold Italic variations.
![image](https://user-images.githubusercontent.com/14205339/64910660-36c37480-d708-11e9-9fe8-24f13693b7fb.png)

May be the ability to change _font style_ should be granted to the user, as in Plasma System Settings, because different amount of boldness of the font may be present (Medium, Semi Bold, Black, Heavy etc), and therefore the user might be dissatisfied with bold variation provided.

**Comment by psifidotos** [comment]
1. I simplified the qml Labels in case that helps for the spacing issue. 
2. For adding more options for the boldness, I dont like the idea of adding such option

**Comment by gikari** [comment]
Thank you.

> For adding more options for the boldness, I dont like the idea of adding such option

Is the font always have a "Bold" style regardless of what font style is used for a general font now? I mean if the "bold" checkbox is ticked of course.
