### ISSUE TITLE
Applet doesn't fill width of panel

### ISSUE THREAD

**Issue by t0msk** [psifidotos/applet-window-title#71]
Hello, I use Latte panel with this applet and it doesn't fill whole panel, only some space.

Here is my layout file: 
[layout.layout.latte.zip](https://github.com/psifidotos/applet-window-title/files/3693429/layout.layout.latte.zip)

Reference: https://www.reddit.com/r/kde/comments/ddleih/fill_width_with_title_window_applet/

**Comment by psifidotos** [comment]
In the top panel you havent placed the buttons_appmenu_title widgets at the far left....

1. right click panel -> Panel Settings
2. Click on, **"Rearrange and Configure your widgets"** button which just about your widgets
3. The Justify alignment uses two splitters, the mentioned applets must be placed/dragged BEFORE the LEFT most Justify alignment spitter

like below:
![image](https://user-images.githubusercontent.com/2216474/66257724-54cf4280-e7a5-11e9-9581-00826f0a0307.png)

**Comment by psifidotos** [comment]
between the Justify Splitters are placed only widgets that you want them at the exact center of your panel

**Comment by t0msk** [comment]
Thank you, now it works :)
