### ISSUE TITLE
UnMaximize window after double click on applet

### ISSUE THREAD

**Issue by t0msk** [psifidotos/applet-window-title#72]
Hello, I used Active Window Control and there was feature, that if you double click on window title, then you unmaximize window to original size like before maximizing, it would be great if you add this feature.

**Comment by psifidotos** [comment]
It is supported from Latte v0.9, and also dragging the last active window

**Comment by t0msk** [comment]
How can I enable it? Because it doesn't work, I have Latte 0.9.3.

**Comment by psifidotos** [comment]
Dock Settings, Behavior, enable, Drag and maximize/restore last active window

**Comment by t0msk** [comment]
Thanks, it works :) It's awesome :)
