### ISSUE TITLE
[Feature Request] Clicking on icon opens Alt-F3 Menu

### ISSUE THREAD

**Issue by sammyspark** [psifidotos/applet-window-title#76]
In stock KDE, when you click the icon in the top left of an application window (in the title bar), the Alt-F3 menu opens up.

Would it be possible to replicate this behavior with the icon in the Latte applet-window-title as well?

**Comment by psifidotos** [comment]
I investigated it and I did not find any solution to call this menu...

**Comment by kn-id** [comment]
What about the Task Manager applet right click menu?
https://github.com/KDE/plasma-desktop/blob/master/applets/taskmanager/package/contents/ui/ContextMenu.qml

**Comment by psifidotos** [comment]
That could be possible but I have no interest implementing it...

Feel free to contribute...

**Comment by psifidotos** [comment]
noone appeared to implement it...
