### ISSUE TITLE
[Feature Request] Make font respect window title font and color from system settings

### ISSUE THREAD

**Issue by Nano-Ocelot** [psifidotos/applet-window-title#77]
Any hope for an an option for the font to be linked to the 'window title' font in system settings instead of the 'general' font? There's no visual consistency between the window title font in the global menu vs the font in titlebars. Even more troubling is that I'd have to change the font basically system wide just to affect this one font, which I believe makes more sense to be linked to window title since it is the window title. Also there doesn't seem to be a way to change the font color. Could this also be linked to the 'titlebar' color in system settings?

**Comment by psifidotos** [comment]
The applet is part of a panel, so changing the font it will break consistency with the neighbor elements.

For the coloring same thing applies but you can use Latte v0.9.x  for this that can color its contents based on the active or touching window

**Comment by Nano-Ocelot** [comment]
I suppose my logic is that if you needed visual consistency with some other
element of the panel you would just set window title font to whatever makes
it consistent instead of the general font. It'd be the same thing just
changing a different font that isn't linked to nearly every other font on
the system. As it stands anyone in my situation can't make their font match
the rest of the panel or titlebars because of the way it is set up. For
instance my panel has very colorful elements and a different font all over
it except for this one bland white font. Also doesn't the latte dock
setting change the whole panel color and not just fonts? If so that's
definitely not what I want. Oh, well. I'll figure something out.

**Comment by psifidotos** [comment]
Yep, titlelayout.qml it is
