### ISSUE TITLE
Can't config applet-window-title on kUbuntu 18.04

### ISSUE THREAD

**Issue by Zardoz89** [psifidotos/applet-window-title#8]
I get an error about missing QtQuickControls and I have installed qml-module-qtquick-controls and  qml-module-qtquick-controls2

![imagen](https://user-images.githubusercontent.com/888483/48414019-c0ea2780-e749-11e8-82fc-f898bd4f2b94.png)

**Comment by psifidotos** [comment]
what is your Qt version ?

**Comment by Zardoz89** [comment]
qt 5.9.5
plasmashell 5.12.6

**Comment by psifidotos** [comment]
fixed with v0.1.1
