### ISSUE TITLE
Add option to disable tooltip

### ISSUE THREAD

**Issue by wsdfhjxc** [psifidotos/applet-window-title#85]
This is a request regarding features proposed in #84. Those features involve interacting with the applet with a mouse cursor. The thing is, a tooltip is popping up every time a mouse cursor is placed over the plasmoid. I find that quite annoying over time, so it'd be great if the tooltip could be disabled.

**Comment by psifidotos** [comment]
use master version, there is already

**Comment by wsdfhjxc** [comment]
Haha, it's literally the latest commit, and I overlooked it...
