### ISSUE TITLE
Soffice.Bin > LibreOffice 

### ISSUE THREAD

**Issue by Sadi58** [psifidotos/applet-window-title#88]
Currently it simply dislays "Soffice.Bin" as app/window name when the user opens LibreOffice Writer, Calc, etc. 
Ideally we would expect "LibreOffice Writer", "LibreOffice Calc" and so on.
At least until this can be achieved, it might be better to add an item to the default configuration to replace "Soffice.Bin" with "LibreOffice".

**Comment by psifidotos** [comment]
https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F

and for substitutions go to Behavior page at applet settings window
