### ISSUE TITLE
Wrong window title in multi-monitor setups

### ISSUE THREAD

**Issue by gondsman** [psifidotos/applet-window-title#89]
Hello, I'm using Plasma 5.18 with latte dock 0.9.9 and the window-title applet version 0.6 and I have an issue with using two monitors.
I have the applet set up so that it only shows the title of the windows on the current monitor though the latte-dock feature. Thius generally works fine with most windows.
However, when I open something "desktop related" like a widget on a latte panel or when I browse through the kickoff menu on one monitor, the title shown on the second monitor changes to "Latte" or "Plasma Desktop Workspace" after a second. This doesn't happen with the window-buttons and window-appmenu applets, which keep referring to the correct window. Same thing happens if I right click on an applet to configure it or open the menu editor by right clicking on my kickoff button on a panel.

I think the correct behaviour would be to not change title when opening a menu, even more because the other applets don't change, so I can see the "Plasma Desktop Workspace" title with the dolphin menubar for example. If the menu opens a configuration window, it should of course show up (like the menu editor), but only on the correct screen, not both.

I hope I was clear enough, I can explain it more in detail if needed.

**Comment by psifidotos** [comment]
Clear enough but I don't think this is solvable.

**Comment by psifidotos** [comment]
And this is not solvable because there is no valid way that I know of for these windows to be blacklisted and be ignored.

**Comment by gondsman** [comment]
Thanks for the reply. What I don't understand then is why the two other applets I use (which are both yours) don't have an issue with it. The global menu is always referring to the right application and the buttons always affect the right window, even when the title is wrong.

**Comment by psifidotos** [comment]
When you use a single monitor don't you have the same issue with this windows?

**Comment by gondsman** [comment]
Yes, in fact I do. It's just a lot more obnoxious with two monitors because closing the menu/applet on the primary monitor doesn't make the wrong title go away on the secondary one.

**Comment by psifidotos** [comment]
btw your comments are not correct. The window buttons applet interferes with Latte/Plasma popups if you cick the close button it closes the popup

**Comment by gondsman** [comment]
I have the buttons set up to only be visible for maximized windows. On the monitor I open the popup they disappear (which means that they "see" the popup as the main window), but on the secondary monitor they stay there and keep controlling the maximized window on the second monitor even though the title says "latte".

**Comment by gondsman** [comment]
If you want I recorded a short screencast with the issue (although I don't know where to upload it).

**Comment by psifidotos** [comment]
1. videos can be uploaded to google drive and dropbox and send here the link
2. the appmenu applet has an internal c++ lib that filters popups under X11 environment. The other two applets can not follow that road...

**Comment by gondsman** [comment]
Oh, too bad. Thanks for the reply anyway.
Is the lack of blacklisting also related to the issue with the secondary monitor? I would assume it's different since the window buttons applet works on the second monitor.
BTW, I uploaded the screencast here to better show the issue:
https://drive.google.com/open?id=1o_GDO9MuPXHlC44xhf-L5IJmgOCZItbi

**Comment by psifidotos** [comment]
ok found it... thank u... I tracked it down to Latte... The fix will part of next 0.9.10 Latte version.

https://phabricator.kde.org/R878:ed7ef5f25904e6d40e58b8c2634df6e4d1770b6a

**Comment by gondsman** [comment]
Thank you for all the work! :)
