### ISSUE TITLE
Feature request: enable scrolling over the window title to maximize/restore window size

### ISSUE THREAD

**Issue by najodleglejszy** [psifidotos/applet-window-title#9]
Right now, double clicking on the applet maximizes the window or restores it to the previous size. It would be great if there was an option to scroll up for maximizing and scrolling down for restoring. It would fit great with Plasma's already existing option that allows you to scroll up over the window's title bar to maximize.

**Comment by psifidotos** [comment]
I will consider it...
whatever be decided for actions it should be also supported from Latte git version also..
Those two should feel the same.

**Comment by najodleglejszy** [comment]
I know it's off-topic, but it would be awesome if Latte dock supported scrolling up/down for maximizing/minimizing windows, too. back when I was using Windows, I've been using a little tool that added that functionality and I'm still wishing I could replicate that setup on Linux.

**Comment by psifidotos** [comment]
> I know it's off-topic, but it would be awesome if Latte dock supported scrolling up/down for maximizing/minimizing windows, too. back when I was using Windows,

Latte git version will change its properties showing and will reorganize them... At that step having Latte options such as the one you discover they will probably be added.

Please add your feature request at: https://bugs.kde.org/enter_bug.cgi?product=latte-dock

mentioning also this thread...
this way I wont forget it...

**Comment by psifidotos** [comment]
not related to applet it should be forwarded to Latte bug tracker as a feature request
