### ISSUE TITLE
[Feature Request] Add Help Menu as a dropdown when Application Name is clicked.

### ISSUE THREAD

**Issue by Jonchun** [psifidotos/applet-window-title#91]
What would make this applet even more amazing is if it could automatically take the help menu from https://github.com/psifidotos/applet-window-appmenu and place it as a dropdown when the App Name is clicked. Perhaps there can be an option/checkbox labeled "Show Help on Click".

Conversely, if this feature is approved, in the Window AppMenu applet, there should be a checkbox/option called "Hide Help Menu" which filters out the Help menu and doesn't display it so it can be used in tandem with this option.

**Comment by psifidotos** [comment]
sorry I dont like it

**Comment by Jonchun** [comment]
No problem. Just in case I wasn't clear, I'll toss a screenshot in here from my Mac to show the effect I wanted to achieve:

![image](https://user-images.githubusercontent.com/5800539/78039507-343f0a00-733c-11ea-8977-dadadb7d3628.png)

At the end of the day, not a huge deal.

**Comment by psifidotos** [comment]
this is not the Help under Linux, it is a special Menu under Mac that does not exist as paradigm under Linux

**Comment by Jonchun** [comment]
Yea I know it's a special menu, but in general, it tends to have things like "About", "Information", etc. I just thought it would be nice to be able to use the application title rather than have it be unclickable. Thank you for your response!
