### ISSUE TITLE
[Feature] Option to only/always show the activity name/icon

### ISSUE THREAD

**Issue by maciex** [psifidotos/applet-window-title#92]
I would like to ask for a simple feature.
An option to show the activity name instead of the application title would be useful. The activity name could be shown always, with the windows title, or only the activity name could be shown.

Adding this would fill the missing functionality in KDE/Plasma, to be able to see on which Activity the use currently is.

**Comment by psifidotos** [comment]
This is already provided when there is no shown window

**Comment by maciex** [comment]
Yes, I know that when there's no windows shown the Activity name is shown.
But I would like the Activity name to be shown, even if there is a window with focus.

**Comment by psifidotos** [comment]
mockups please for what you are describing

**Comment by psifidotos** [comment]
Actually thinking it again you need a plasma applet that is always shown activity name and icon so this is totally out of scope if this applet.
