### ISSUE TITLE
[Feature] Add fixed width that allows aplets to go next to it.

### ISSUE THREAD

**Issue by StarrKiss** [psifidotos/applet-window-title#94]
Perhaps cut-off is a better term. I am using the window app menu with the window applet menu. When I set the fixed width feature, it works great with longer windows, but it ALSO pushes the window menu applet too far to the right:
![image](https://user-images.githubusercontent.com/13007697/79467477-56e44a80-7fed-11ea-8d43-24f72d56b3d0.png)

Could an option be added that cuts off the window title at a set number of characters while still having applets next to it go next to smaller titles? Thanks

**Comment by psifidotos** [comment]
1. Show me a screenshot of your window title settings
2. It should be just fine by setting the maximum length
3. Are you using Plasma or Latte panel?
4. If you are using Plasma panel you need  spacer to push appmenu backwards, have you added it?

**Comment by StarrKiss** [comment]
I am using Latte Panel, here is a screenshot if the settings:
![image](https://user-images.githubusercontent.com/13007697/79485039-1e9c3680-8004-11ea-8f2b-ae9da10556b4.png)

**Comment by psifidotos** [comment]
🙂 This is NOT Window Title applet, you are using Application Title which is a different applet!
