### ISSUE TITLE
Behavior of Middle Click

### ISSUE THREAD

**Issue by kaiiiz** [psifidotos/applet-window-title#95]
When I'm using Chrome, I always close the tab by using middle click, and I often accidentally touch the windows title and the whole Chrome is closed. :(

Is there any option to choose the behavior of middle click? (close the active window)

**Comment by psifidotos** [comment]
Latte git version provides an option to Close Active Window with middle click from  panel empty areas and applets that have not any other behavior for middle click...

**Comment by kaiiiz** [comment]
To ensure there is no other config conflicting to the plugin, I do a fresh installation using Arch Linux with plasma-5.18.4.1-1, kdeclarative-5.69.0-1. And just install the plugin from https://aur.archlinux.org/packages/plasma5-applets-window-title without latte, but still get the same result.

I found the closest setting in system setting is 'Window Behavior' > 'Titlebar Actions', but the default behavior of middle click is 'Do nothing'.

![image](https://user-images.githubusercontent.com/30596812/80241744-acef6880-8653-11ea-8a23-035d33cbcef7.png)

Is there any default behavior existing in plasma desktop?
