### ISSUE TITLE
Width changes after reboot on secondary monitor

### ISSUE THREAD

**Issue by wazlecracker** [psifidotos/applet-window-title#96]
I have 2 monitors and on my secondary, right one, the title changes to a fixed width after every reboot like this:
![image](https://user-images.githubusercontent.com/45174508/80643594-dfd09c80-8a57-11ea-8f06-d3dc0ef6f419.png)
I fix it by going to Configure Window Title > Appearance > Check 'Fill available space', save, then uncheck and save again. This is what it should look like:
![image](https://user-images.githubusercontent.com/45174508/80643850-4655ba80-8a58-11ea-9ed0-96dd6cac655b.png)

**Comment by psifidotos** [comment]
Latte or Plasma panel?

**Comment by wazlecracker** [comment]
Plasma, 5.18.4.1-1

**Comment by psifidotos** [comment]
The applet is inside a Latte or Plasma panel?

**Comment by wazlecracker** [comment]
It's inside a Plasma panel. Should I try a latte one?

**Comment by wazlecracker** [comment]
Changing to a Latte panel solves the issue.
