### ISSUE TITLE
[feature] - relative thickness for icon

### ISSUE THREAD

**Issue by MichaelP89** [psifidotos/applet-window-title#97]
It would be nice if i could define a relative thickness for the icon. (e.g. 80% of the panel)
If i use "Fill thickness" there is no spacing on top and bottom of the icon which does not look good.
When i set the thickness in pixel it does not scale when the panel is resized, what i do often, because I'm using different monitors.

Greetings
Michael

**Comment by psifidotos** [comment]
Such option will give you blurred icons at most cases.

**Comment by MichaelP89** [comment]
Ok, because the icons are available only in fixed dimensions i guess?
Then it would be cool to configure a minimal top und bottom margin of the icon (in pixel or percent of the panel height) when "Fill thickness" is used.

Because as i said with "Full thickness" to me it happend, that there was absolutely no space on top and bottom of the icon which does not look good.

Greetings
Michael

**Comment by MichaelP89** [comment]
By the way, I'm using latte panel, there is an option to configure the top and bottom padding of the panel, it would be even better if that would be considered for the shown icon, if that is possible.

**Comment by psifidotos** [comment]
Starts to become too messy, sorry I don't think I will proceed with this.

**Comment by psifidotos** [comment]
That is fixed with latest Latte git version. In latest Latte git version, applets specified thickness margin is forced and respected to all applets.
