### ISSUE TITLE
Show activity information gets reset on reboot

### ISSUE THREAD

**Issue by rodrigopedra** [psifidotos/applet-window-title#99]
Hi @psifidotos , thanks for the great widgets use them on my setup and it works very well.

I noticed from some updates ago (can't remember when), when I reboot the option to "Show activity information" gets reset to the default (unchecked) when I reboot or restart the user session.

Below is a screenshot to show which option I am referring to:

![image](https://user-images.githubusercontent.com/5470108/84160727-e6820480-aa44-11ea-8f0d-b116e2916c0a.png)

If you have a hint on how to solve this issue I can try sending a PR.

Thanks again!

**Comment by psifidotos** [comment]
Can you please provide BEFORE and AFTER screenshots to understand which exactly value is lost ?

**Comment by rodrigopedra** [comment]
Hi @psifidotos thanks for your response.

The screenshot from my first post is BEFORE rebooting.

The following screenshot is AFTER rebooting:

![image](https://user-images.githubusercontent.com/5470108/103463740-63d8d380-4d0d-11eb-8236-5b70642f5b0d.png)

The option I am referring to is the one after the label **"Placholder:"**, where there is a checkbox with a label after it reading **"Show activity information"**

Thanks for your help. Let me know if you need more info or any help.

**Comment by psifidotos** [comment]
As you are using Latte...
If you close Latte and start it again is the loss happening again?

**Comment by rodrigopedra** [comment]
Yes. Just tried it by killing the process and the option is reset after restarting Latte.

**Comment by psifidotos** [comment]
1. Are you using Multiple Layouts in Latte
2. If you ade a second window title for testing purposes, same thing happens?
3. Are you using latest master version?

**Comment by rodrigopedra** [comment]
I just figure out what I was doing wrong, just for completeness I will answer the questions you made.

1. No
2. More on this later
3. Yes

When trying out item number 2, I realized I had my layout "locked" on my Latte config. After unlocking the layout the option persisted across restarting Latte and rebooting the machine.

Sorry for the misreport and thank you for your time.

**Comment by psifidotos** [comment]
yeah... no worries, in git version Locked tag has been renamed to ReadOnly in order to help users understand what is doing.
